### ISSUE TITLE
Thumbnail generation with nvidia/cuda hardware acceleration broken since v0.16.1

### ISSUE THREAD

**Issue by Remboooo** [AirenSoft/OvenMediaEngine#1493] opened 2024-01-05 15:21 UTC
**Describe the bug**
Since commit [1704f2e2](https://github.com/AirenSoft/OvenMediaEngine/commit/1704f2e212a514a6eae84c3d6c0766d263320fe8), thumbnail generation using an `<Image>` encode does not work when using hardware acceleration with nvidia/cuda

The bug changed over time. Everything worked up to and including commit [71798fbb](https://github.com/AirenSoft/OvenMediaEngine/commit/71798fbb8ebf13e6c068489c2579a63785897928).

Then [commit 1704f2e2](https://github.com/AirenSoft/OvenMediaEngine/commit/1704f2e212a514a6eae84c3d6c0766d263320fe8) broke it with [the following log](https://github.com/AirenSoft/OvenMediaEngine/files/13843409/ome-1704f2e.txt). The relevant message I think is `Could not create encoder. Encoder(3), OutputTrack(3)`. In this commit, all the output streams seem broken when this occurs.

The following commit is 9df362a8, which changed nothing.

Then the next commit is [8e30856a](https://github.com/AirenSoft/OvenMediaEngine/commit/8e30856a5e346d4f03fab8464415785028989537) which changed the log to `Invalid output format rgba for hwframe download.`. This same error is present in v0.16.1 and persists until the current version (v0.16.3): 
[ome-0.16.3.txt](https://github.com/AirenSoft/OvenMediaEngine/files/13843566/ome-0.16.3.txt)

It seems the root cause is `[2024-01-05 15:58:05.556] I [Dech264NV:3280711] Transcoder | filter_rescaler.cpp:290  | Rescaler parameters [#0 -> #3][nvenc -> nvenc]. input: video_size=1920x1080:pix_fmt=23:time_base=1/1000:pixel_aspect=1/1 -> outputs: fps=fps=1.00:round=near,hwupload_cuda=device=0,scale_cuda=w=1280:h=720,hwdownload,settb=1/90000,format=rgba`

which specifies an output format of `rgba` that is not supported with hwdownload.

**To Reproduce**
1: Run an nvenc-enabled build on a server with an Nvidia GPU. In Server.xml, enable `<HardwareAcceleration>true</HardwareAcceleration>` in the application output profile and add `<Image><Codec>png</Codec><Framerate>1</Framerate></Image>` to the `<Encodes>` section

2: Start the stream

3: See the following errors in the log (in OME v0.16.1): 
```
[2024-01-05 15:44:19.383] E [Dech264NV:3266480] FFmpeg | third_parties.cpp:111  | [hwdownload: 0x7fca56ff0300] Invalid output format rgba for hwframe download.
[2024-01-05 15:44:19.383] E [Dech264NV:3266480] FFmpeg | third_parties.cpp:111  | [AVFilter: 0x7fca5cc287c0] Failed to configure output pad on Parsed_hwdownload_3
[2024-01-05 15:44:19.383] E [Dech264NV:3266480] Transcoder | filter_rescaler.cpp:294  | Could not validate filter graph for rescaling: -22
[2024-01-05 15:44:19.383] E [Dech264NV:3266480] Transcoder | transcoder_filter.cpp:77   | Could not create filter
[2024-01-05 15:44:19.383] E [Dech264NV:3266480] Transcoder | transcoder_stream.cpp:910  | [#default#bam/rem(100)] Failed to create filter. Filter(3)
```

**Expected behavior**
Should work the same as in 0.16.0.
Interestingly, even though it seems to be caused by a scaling filter, it still errors when the configuration does not specify any scaling.

**Logs**
In version 0.16.3: [ome-0.16.3.txt](https://github.com/AirenSoft/OvenMediaEngine/files/13843566/ome-0.16.3.txt)
At commit 1704f2e2 (the first commit in which it is broken): [ome-1704f2e.txt](https://github.com/AirenSoft/OvenMediaEngine/files/13843409/ome-1704f2e.txt).

**Server**
 - OS: Ubuntu 22.04
 - OvenMediaEngine Version: v0.16.1 - v0.16.3
 - Branch: master

**Player**
 - Device: PC
 - OS: Windows 11
 - Browser: Chrome / Firefox
 - Version: 0.10.31

**Additional context**
Using a NVIDIA GeForce GTX 1650 SUPER for hardware acceleration

**Comment by Remboooo** [comment] 2024-01-05 15:47
I tried in the latest master commit 9e578d1c8fa7adf61899ba64a9f26a0032c29c0e and it seems the scaling logic has completely changed (`scale_cuda` is no longer used, in stead it tries `scale_npp`), but it is still broken:
```
[2024-01-05 16:43:16.882] I [Dech264NV:3325132] Transcoder | transcoder_encoder.cpp:277  | The encoder has been created successfully. track(#2), codec(H264), module(nvenc:0)
[2024-01-05 16:43:16.894] I [Dech264NV:3325132] Transcoder | transcoder_encoder.cpp:277  | The encoder has been created successfully. track(#1), codec(H264), module(nvenc:0)
[2024-01-05 16:43:16.895] I [Dech264NV:3325132] Transcoder | transcoder_encoder.cpp:277  | The encoder has been created successfully. track(#3), codec(PNG), module(nvenc:0)
[2024-01-05 16:43:16.895] I [Dech264NV:3325132] Transcoder | filter_rescaler.cpp:297  | Rescaler parameters. track(#0 -> #2), module(nvenc:0 -> nvenc:0). desc(src:video_size=1920x1080:pix_fmt=cuda:time_base=1/1000:pixel_aspect=1/1:frame_rate=30/1 -> output:fps=fps=30.00:round=near,settb=1/90000,scale_npp=1280:720,format=cuda)
[2024-01-05 16:43:16.897] I [Dech264NV:3325132] Transcoder | filter_rescaler.cpp:297  | Rescaler parameters. track(#0 -> #1), module(nvenc:0 -> nvenc:0). desc(src:video_size=1920x1080:pix_fmt=cuda:time_base=1/1000:pixel_aspect=1/1:frame_rate=30/1 -> output:settb=1/90000,scale_npp=1920:1080,format=cuda)
[2024-01-05 16:43:16.898] I [Dech264NV:3325132] Transcoder | filter_rescaler.cpp:297  | Rescaler parameters. track(#0 -> #3), module(nvenc:0 -> nvenc:0). desc(src:video_size=1920x1080:pix_fmt=cuda:time_base=1/1000:pixel_aspect=1/1:frame_rate=30/1 -> output:fps=fps=1.00:round=near,settb=1/90000,scale_npp=1920:1080,format=rgba)
[2024-01-05 16:43:16.899] E [Dech264NV:3325132] FFmpeg | third_parties.cpp:111  | Impossible to convert between the formats supported by the filter 'Parsed_scale_npp_2' and the filter 'auto_scale_0'
[2024-01-05 16:43:16.899] E [Dech264NV:3325132] Transcoder | filter_rescaler.cpp:326  | Could not validate filter graph for rescaling
[2024-01-05 16:43:16.899] E [Dech264NV:3325132] Transcoder | transcoder_filter.cpp:77   | Could not create filter
[2024-01-05 16:43:16.899] E [Dech264NV:3325132] Transcoder | transcoder_stream.cpp:921  | [#default#bam/rem(100)] Failed to create filter. Filter(3)
```

**Comment by Remboooo** [comment] 2024-01-05 22:33
A workaround that works for me for now is to disable hardware processing of the image pipeline altogether:
```patch
diff --git a/src/projects/transcoder/transcoder_encoder.cpp b/src/projects/transcoder/transcoder_encoder.cpp
index 650a29cf..dd67a51d 100644
--- a/src/projects/transcoder/transcoder_encoder.cpp
+++ b/src/projects/transcoder/transcoder_encoder.cpp
@@ -60,7 +60,8 @@ std::shared_ptr<std::vector<std::shared_ptr<CodecCandidate>>> TranscodeEncoder::
        std::shared_ptr<std::vector<std::shared_ptr<CodecCandidate>>> candidate_modules = std::make_shared<std::vector<std::shared_ptr<CodecCandidate>>>();

        // If the track is not video, the default module is the only candidate.
-       if (track->GetMediaType() != cmn::MediaType::Video)
+       // WORKAROUND FOR https://github.com/AirenSoft/OvenMediaEngine/issues/1493: disable hardware processing for image codecs
+       if (track->GetMediaType() != cmn::MediaType::Video || cmn::IsImageCodec(track->GetCodecId()))
        {
                candidate_modules->push_back(std::make_shared<CodecCandidate>(track->GetCodecId(), cmn::MediaCodecModuleId::DEFAULT, 0));
                return candidate_modules;
```

A better solution would be to still do the scaling using `scale_npp` and insert `hwupload_cuda`/`hwdownload` at the correct spots in the filter chain, but I don't nearly know enough about the OME internals to develop that patch myself.

**Comment by Keukhan** [comment] 2024-01-07 12:22
@Remboooo 
Thank you for reporting.
I modified and committed as follows. In the future, I plan to improve it so that it can be filtered only for codecs supported by hardware. 

When using hwupload and hwdownload, there is copy overhead between CPU and GPU, and since CU is used, it is expected to have an impact when using encoding at maximum performance.  So, I plan to support JPEG/PNG encoding on GPU without memory copy. 

Happy New Year!

https://github.com/AirenSoft/OvenMediaEngine/commit/81c34435c58dab1f501b213c65b254dc0c59776c

**Comment by getroot** [comment] 2024-03-15 06:43
This patch made it into the 0.16.5 release. If the issue reproduces, please reopen the issue. Thank you.

**Closed by getroot** 2024-03-15 06:43 UTC
Labels: bug, patched
