### ISSUE TITLE
Could not parse H264 Nal unit header (android chrome)

### ISSUE THREAD

**Issue by donghyun0910** [AirenSoft/OvenMediaEngine#1011] opened 2023-02-02 05:13 UTC
**Describe the bug**
Could not parse H264 Nal unit header.

**To Reproduce**
1. Transmit webRTC Streaming from Android terminal.
2. See error

**Expected behavior**
It is impossible to play the h264 video transmitted by webrtc from the Android terminal through webrtc on the receiving side.

**Logs**
[02-02 13:58:14.599] I [SPRtcSig-T9102:767034] HttpServer | http_server.cpp:146  | Client(<ClientSocket: 0x7fd980001b20, #232, Connected, TCP, Nonblocking, x.x.x.x:47566>) is connected on *:9102
[02-02 13:58:14.611] I [SPRtcSig-T9102:767034] HttpServer | http_connection.cpp:147  | TLS connection accepted : Server Name(airtc.uangel.com) Alpn Protocol(http/1.1) Client (<ClientSocket: 0x7fd980001b20, #232, Connected, TCP, Nonblocking, x.x.x.x:47566>)
[02-02 13:58:14.613] I [SPRtcSig-T9102:767034] Signalling | rtc_signalling_server.cpp:231  | New client is connected: <ClientSocket: 0x7fd980001b20, #232, Connected, TCP, Nonblocking, x.x.x.x:47566>
[02-02 13:58:14.657] I [SPRtcSig-T9102:767034] Provider | stream.cpp:49   | Unknown/kYspWDZH(100) has been started stream
[02-02 13:58:14.657] I [SPRtcSig-T9102:767034] MediaRouter | mediarouter_application.cpp:255  | [#default#app/kYspWDZH(100)] Trying to create a stream
[02-02 13:58:14.657] I [SPRtcSig-T9102:767034] MediaRouter | mediarouter_stream.cpp:54   | [#default#app/kYspWDZH(100)] Trying to create a mediarouter stream
[02-02 13:58:14.657] I [SPRtcSig-T9102:767034] Monitor | application_metrics.cpp:57   | Create StreamMetrics(kYspWDZH/af25d21d-300c-4d68-8c9f-5624bc41f247/default/#default#app/kYspWDZH/i) for monitoring
[02-02 13:58:14.657] I [SPRtcSig-T9102:767034] Transcoder | transcoder_stream.cpp:626  | [#default#app/kYspWDZH(100)] Output stream has been created. [#default#app/kYspWDZH(427482635)]
[02-02 13:58:14.658] I [SPRtcSig-T9102:767034] Transcoder | transcoder_stream.cpp:86   | No decoder generated
[02-02 13:58:14.658] I [SPRtcSig-T9102:767034] MediaRouter | mediarouter_application.cpp:255  | [#default#app/kYspWDZH(427482635)] Trying to create a stream
[02-02 13:58:14.658] I [SPRtcSig-T9102:767034] MediaRouter | mediarouter_stream.cpp:54   | [#default#app/kYspWDZH(427482635)] Trying to create a mediarouter stream
[02-02 13:58:14.658] I [SPRtcSig-T9102:767034] Monitor | application_metrics.cpp:57   | Create StreamMetrics(kYspWDZH/af25d21d-300c-4d68-8c9f-5624bc41f247/default/#default#app/kYspWDZH/o) for monitoring
[02-02 13:58:14.658] I [SPRtcSig-T9102:767034] Transcoder | transcoder_stream.cpp:92   | [#default#app/kYspWDZH(100)] Transcoder stream has been started.
[02-02 13:58:14.759] I [SPICE-T13478:767052] ICE | ice_port.cpp:479  | Turn client has connected : <ClientSocket: 0x7fd950001b20, #233, Connected, TCP, Nonblocking, x.x.x.x:58876>
[02-02 13:58:14.759] I [SPICE-T13478:767053] ICE | ice_port.cpp:479  | Turn client has connected : <ClientSocket: 0x7fd9500020d0, #234, Connected, TCP, Nonblocking, x.x.x.x:58874>
[02-02 13:58:14.775] I [SPICE-T13478:767052] ICE | ice_port.cpp:779  | Add the client to the port list: x.x.x.x:58876 / Packet type : STUN GateType : SEND_INDICATION
[02-02 13:58:14.002] I [SPAPISvr-T9103:767253] HttpServer | http_server.cpp:146  | Client(<ClientSocket: 0x7fd928001f60, #235, Connected, TCP, Nonblocking, y.y.y.y:46056>) is connected on *:9103
[02-02 13:58:15.343] E [InboundWorker:767161] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header
[02-02 13:58:15.373] E [InboundWorker:767161] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header
[02-02 13:58:15.444] E [InboundWorker:767161] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header
[02-02 13:58:15.487] E [InboundWorker:767161] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header
[02-02 13:58:15.556] E [InboundWorker:767161] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header
[02-02 13:58:15.592] E [InboundWorker:767161] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header
[02-02 13:58:15.652] E [InboundWorker:767161] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header
[02-02 13:58:15.686] E [InboundWorker:767161] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header
[02-02 13:58:15.757] E [InboundWorker:767161] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header
[02-02 13:58:15.793] E [InboundWorker:767161] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header
[02-02 13:58:15.859] E [InboundWorker:767161] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header
[02-02 13:58:15.892] E [InboundWorker:767161] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header
[02-02 13:58:15.960] E [InboundWorker:767161] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header

**Server (please complete the following information):**
 - OS: Ubuntu
 - OvenMediaEngine Version: v0.15.0
 - Branch: release

**Player (please complete the following information):**
 - Device: Galaxy Tab S7+
 - OS: Android 12
 - Browser: chrome browser
 - Version: 107.0.5304.141

**Additional context**
source: src/projects/modules/bitstream/h264/h264_parser.cpp
function: bool H264Parser::ParseNalUnitHeader(NalUnitBitstreamParser &parser, H264NalUnitHeader &header)
Description: Not supported for forbidden_zero_bit = 1

**Comment by getroot** [comment] 2023-02-02 05:34
Thanks for reporting the problem.

According to https://www.rfc-editor.org/rfc/rfc3984#section-1.3 `forbidden_zero_bit` must be zero.
This is so strange because all chrome I've used so far has never violated this and works fine with OME.
Chrome on my Galaxy Note 10 works well with OME. Does the problem reproduce on https://space.ovenplayer.com/?

**Comment by getroot** [comment] 2023-02-02 05:39
Oh one of our developers had a Galaxy Tab S7 so I tested it. But the problem was not reproduced. Chrome version is 109.0.5414.118. Chrome 107 version is not available so I couldn't test it with it.

**Comment by umeshshende** [comment] 2023-02-02 05:52
Im facing the same issue when android chrome stream with 1080 and consuming through window chrome browser ovenplayer

[2023-02-02 05:41:50.582] I [SPRtcSig-T3334:1412] MediaRouter | mediarouter_application.cpp:255  | [#default#app/stream1234(100)] Trying to create a stream
[2023-02-02 05:41:50.582] I [SPRtcSig-T3334:1412] MediaRouter | mediarouter_stream.cpp:54   | [#default#app/stream1234(100)] Trying to create a mediarouter stream
[2023-02-02 05:41:50.582] I [SPRtcSig-T3334:1412] Monitor | application_metrics.cpp:57   | Create StreamMetrics(stream1234/9532f7f2-2727-4efe-97f4-ff4c981d510b/default/#default#app/stream1234/i) for monitoring
[2023-02-02 05:41:50.582] I [SPRtcSig-T3334:1412] Transcoder | transcoder_stream.cpp:626  | [#default#app/stream1234(100)] Output stream has been created. [#default#app/stream1234(3673801426)]
[2023-02-02 05:41:50.583] I [SPRtcSig-T3334:1412] MediaRouter | mediarouter_application.cpp:255  | [#default#app/stream1234(3673801426)] Trying to create a stream
[2023-02-02 05:41:50.583] I [SPRtcSig-T3334:1412] MediaRouter | mediarouter_stream.cpp:54   | [#default#app/stream1234(3673801426)] Trying to create a mediarouter stream
[2023-02-02 05:41:50.583] I [SPRtcSig-T3334:1412] Monitor | application_metrics.cpp:57   | Create StreamMetrics(stream1234/9532f7f2-2727-4efe-97f4-ff4c981d510b/default/#default#app/stream1234/o) for monitoring
[2023-02-02 05:41:50.583] I [SPRtcSig-T3334:1412] Transcoder | transcoder_stream.cpp:92   | [#default#app/stream1234(100)] Transcoder stream has been started.
[2023-02-02 05:41:50.788] I [SPICE-T3478:1421] ICE | ice_port.cpp:479  | Turn client has connected : <ClientSocket: 0x7fa745400010, #32, Connected, TCP, Nonblocking, ipaddress:36318>
[2023-02-02 05:41:50.788] I [SPICE-T3478:1421] ICE | ice_port.cpp:479  | Turn client has connected : <ClientSocket: 0x7fa745400410, #33, Connected, TCP, Nonblocking, ipaddress:36314>
[2023-02-02 05:41:50.997] I [SPICE-T3478:1421] ICE | ice_port.cpp:779  | Add the client to the port list: ipaddress:36318 / Packet type : STUN GateType : SEND_INDICATION
[2023-02-02 05:41:51.049] I [SPICE-T3478:1421] ICE | ice_port.cpp:783  | Update the client to the port list: to  ipaddress:36314 from  ipaddress:36318
[2023-02-02 05:41:51.855] E [InboundWorker:1430] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header
[2023-02-02 05:41:51.871] E [InboundWorker:1430] MediaRouter | mediarouter_stream.cpp:349  | Could not parse H264 Nal unit header

**Comment by getroot** [comment] 2023-02-02 06:14
Oh... when I tried to broadcast at 1080p resolution on my Galaxy Tab 7, it reproduced. I'll look into this soon. 
In my environment, broadcasting at auto resolution or 720p resolution worked well.

**Comment by umeshshende** [comment] 2023-02-02 06:16
Yes its issue is present for 1080p

**Comment by donghyun0910** [comment] 2023-02-02 06:38
Yes, it only happens in Full HD.

In the following function, Full HD works without errors.

navigator.mediaDevices.getUserMedia(constraints)

Did the operation test with automatic resolution be set to operate below HD resolution?

Is there any solution to defend against this issue?

**Comment by getroot** [comment] 2023-02-02 07:41
After testing several things, it seems that H.264/1080p encoding is actually failing on that Android device. This can be fixed by changing the codec to VP8. For reference, H.264/1080p works normally on the iPhone 12 mini. To change the codec to VP8, modify the answer SDP's m line so that the vp8 codec is placed first, or delete the attributes related to h.264. (Currently, h.264 is placed in front.)

When you set the resolution automatically in OvenLiveKit, the browser starts with a lower resolution/bitrate and continuously changes to the optimal resolution and bitrate considering system resources and network bandwidth. (Of course, even if you set the resolution, it does not always work with a fixed resolution.)

Later, when I have time, I'll do some more research on how WebRTC works on Android devices.

**Comment by getroot** [comment] 2023-03-13 02:05
For devices that do not support 1080p encoding with H.264, we have added a Preferred video codec option. This problem is mostly solved by selecting VP8.

![image](https://user-images.githubusercontent.com/17779085/224591739-cc21ba28-cca2-40ab-9e7a-7594a99753f9.png)

**Closed** 2023-04-10 11:11 UTC
Labels: wontfix
