### ISSUE TITLE
OME is not using persistent TCP connection for delivering LLDASH

### ISSUE THREAD

**Issue by jplogos** [AirenSoft/OvenMediaEngine#564] opened 2021-11-17 09:11 UTC
**PROBLEM**

OME version: 0.12.1
We are using LLDASH feature in OME. 
We see that OME is closing the connection to client(OME player) with [FIN, ACK] soon after each segment delivery. 
As per the pcap trace we see the different TCP ports and that is of the fact that after each segment delivery the OME is closing the connection by issuing the [FIN, ACK].  please refer the attached image.

![OME pcap trace image](https://user-images.githubusercontent.com/38765075/142170520-89713d99-a95c-47dd-a535-3916991f0253.png)

**EXPECTATION**
We would like to know how to avoid OME closing the TCP connections after each segment delivery.
Also, is there any configuration available in OME to use persistent connections

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information
OME version: 0.12.1

- Operating system and version

CentOS Linux release 7.9.2009 (Core)

**Comment by getroot** [comment] 2021-11-17 09:24
The latest release version of OME is 0.12.8.
Would you like to see if it is reproduced with the latest version as well?

**Comment by getroot** [comment] 2021-11-17 09:38
We've been too busy these days to do much on OME, but TCP keep-alive is one of our high priority tasks on our roadmap.
https://github.com/AirenSoft/OvenMediaEngine/issues/548

**Comment by basisbit** [comment] 2021-11-21 10:57
This is a duplicate of #279

**Closed** 2022-01-17 07:25 UTC
Labels: help
