### ISSUE TITLE
OME crash after enabling DVR

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#983] opened 2022-12-25 02:57 UTC
Merry Christmas, I got you a bug report @getroot 🎅🎄

**Describe the bug**
After several hours running, OME ~crashed (with no actual crash, as far as I can tell, it just stopped working)

We are using OME with docker, on the most recent dev as of this comment - 

`FROM airensoft/ovenmediaengine@sha256:afe69f2b52191cb32b17d8e6b5b044f1493f9b2893f2da11a922c9fd469d7879`

**Logs**
OME log, lots of chaff in here I think. The crash was at approximately 02:10 in the logs timestamps
[DVRcrash.zip](https://github.com/AirenSoft/OvenMediaEngine/files/10299374/DVRcrash.zip)

Server.xml https://gist.github.com/naanlizard/36bc4e275699e4bc0de97dd5ac445f5d

Stats - you can see when the latest instance (precrash) of OME was started shortly after 12:00, then crashed about 45 minutes ago, and recently I restarted OME again and things are once more smooth. I'll let you know if it keeps happening and we roll back to no DVR (on the same version)

**Comment by naanlizard** [comment] 2022-12-25 21:50
We are also seeing higher and more erratic memory usage, though I don't think it's leaking

https://i.imgur.com/YJTrF95.png

**Comment by naanlizard** [comment] 2022-12-27 15:59
FWIW, no problems since the first one

**Comment by getroot** [comment] 2022-12-29 02:16
What does stopped working mean? Is the new RTMP input or LLHLS playback not working? Could it have something to do with storage? The DVR function uses a lot of storage, so slow or insufficient storage can be a problem.

Or maybe it's an issue with https://github.com/AirenSoft/OvenMediaEngine/issues/981? This is a problem with WebRTC playback not working at some point and I haven't solved this yet (because I'm on vacation right now).

**Comment by naanlizard** [comment] 2022-12-29 02:21
Storage is an ssd, and only one person was watching with dvr/llhls (my test stream) though others may have been using llhls and unable to seek (our production player does not support it yet)

rtmp input may have worked, but I think not. There were many streams that were not forwarded. Some WERE forwarded, but none were able to be played via webrtc or llhls. 

I was hoping the logs would show something obvious

**Comment by getroot** [comment] 2022-12-29 02:27
Regardless of viewing the DVR, if the LLHLS DVR is activated in the application, all streams within the application are recorded and saved as files.

If it's a deadlock problem without a crash, it might be related to #981, regardless of the DVR. I'm looking into this after I get back to work. Thanks for the report.

**Comment by getroot** [comment] 2023-01-03 07:04
happy new year!

Has this problem reproduced again? I haven't been able to reproduce it yet. #981 doesn't seem to be related (it seems to be an OriginMapStore issue).

**Comment by naanlizard** [comment] 2023-01-03 15:10
So far no more problems. Nothing in the log looks suspicious?

I’ll close this if you think I should and reopen if it happens again

**Comment by getroot** [comment] 2023-01-04 01:54
I couldn't find anything suspicious in the logs.
Please close the issue and open it again with a new log when it reproduces again.

**Closed** 2023-01-04 01:54 UTC
Labels: bug
