### ISSUE TITLE
Error in bandwidth

### ISSUE THREAD

**Issue by gregfr** [AirenSoft/OvenMediaEngine#1132] opened 2023-03-13 15:04 UTC
**Describe the bug**
Greetings
I've upgrade to 0.15.3 and there's something weird with the bandwidth.

Here is the config file:
```
								<Video>
									<Name>video_1080</Name>
									<Codec>h264</Codec>
									<Bitrate>3824000</Bitrate>
									<Framerate>25</Framerate>
									<Width>1920</Width>
									<Height>1080</Height>
									<Preset>faster</Preset>
								</Video>
								<Video>
									<Name>video_720</Name>
									<Codec>h264</Codec>
									<Bitrate>2024000</Bitrate>
									<Framerate>25</Framerate>
									<Width>1280</Width>
									<Height>720</Height>
									<Preset>faster</Preset>
								</Video>
```

Running 0.15.2, the HLS is:
```
#EXT-X-STREAM-INF:BANDWIDTH=4038915,RESOLUTION=1920x1080,FRAME-RATE=24.958,CODECS="avc1.42c028,mp4a.40.2",AUDIO="aac_256"
#EXT-X-STREAM-INF:BANDWIDTH=1980843,RESOLUTION=1280x720,FRAME-RATE=25.015,CODECS="avc1.42c01f,mp4a.40.2",AUDIO="aac_256"
```

Running 0.15.3, it is:
```
#EXT-X-STREAM-INF:BANDWIDTH=1173618,RESOLUTION=1920x1080,FRAME-RATE=25.008,CODECS="avc1.42c028,mp4a.40.2",AUDIO="aac_256"
#EXT-X-STREAM-INF:BANDWIDTH=644357,RESOLUTION=1280x720,FRAME-RATE=25.012,CODECS="avc1.42c01f,mp4a.40.2",AUDIO="aac_256"
```

The input stream is exactly the same (the bunny steamed at 6Mbps from OBS).
The corresponding image quality is consistent (good with 0.15.2, bad with 0.15.3).

Did I miss something?

Thanks in advance

Regards

**To Reproduce**
1. Set Server.xml as follows '...'
2. With Encoder '...' [e.g. Use OBS Version] 
3. See error

**Expected behavior**

**Logs**
Please upload the entire OvenMediaEngine.log. You may delete important personal information.

**Server (please complete the following information):**
 - OvenMediaEngine Version: [e.g. v0.10.1]
 - Branch: [e.g. dev]

**Player (please complete the following information):**
 - Device: [e.g. iPhone 8]

**Additional context**

**Comment by getroot** [comment] 2023-03-13 15:41
Please share your OBS encoding settings so I can reproduce your problem

**Comment by gregfr** [comment] 2023-03-13 16:22
Here it is :)

![image](https://user-images.githubusercontent.com/361582/224763207-da835c5b-bc37-4e85-8a99-0ba4f0d98529.png)

I'm streaming with SRT ; I'll test more (including RTMP) tomorrow.

Thanks!

**Comment by Keukhan** [comment] 2023-03-14 06:41
@gregfr 

During the release from version 0.15.2 to 0.15.3 the **Video.Preset** parameter of the openh264 encoder has been changed.
To solve the above issue, change the preset value from faster -> medium.
Please test again.

Thanks

0.15.2
![image](https://user-images.githubusercontent.com/21077363/224915873-1997459f-7168-42ab-b294-30335f952fca.png)

0.15.3
![image](https://user-images.githubusercontent.com/21077363/224915975-7b099a92-d732-4a68-83be-0c50bdaf6e28.png)

**Comment by Keukhan** [comment] 2023-03-19 10:47
@gregfr 

It has been improved so that the bandwidth can be displayed as the value set by the user in the HLS Manifest. 
Try testing with version 0.15.5.

Thanks.

**Comment by getroot** [comment] 2023-04-05 12:35
@gregfr Please review this issue and close it if you think it has been resolved.

**Comment by basisbit** [comment] 2023-04-08 15:08
@gregfr By the way, if you use a current version of OBS, you'll want to add the x264 option `bf=0` in OBS, because the b-frames option of more recent ffmpeg was renamed.

**Closed** 2023-05-18 14:28 UTC
Labels: bug, patched, resolved

**Comment by gregfr** [comment] 2023-10-13 06:54
Thanks a lot. I can't believe it's been 6 months already! I'll test that ASAP, sorry!
