### ISSUE TITLE
RTSPpull not create stream when ovt requeat  from edge

### ISSUE THREAD

**Issue by veraphon** [AirenSoft/OvenMediaEngine#246] opened 2020-12-31 09:14 UTC
Ovenmediaengine 0.10.10
Ubuntu 18.04

RTSP encoader < Origin < ovt < Edge  < Webrtc Client  Not working

RTSP create stream when some client view 1 webrtc or hls or dash from origin and ovt work

RTSP encoader < Origin < ovt < Edge  < Webrtc Client it work
                               ^
                               ^
                               ^
                               ^
                             Webrtc Client  1 connection to origin

**Comment by getroot** [comment] 2020-12-31 09:49
I need your origin's Server.xml, edge's Server.xml and ovenmediaengine.log when errors occur to anlyze this problem

**Comment by veraphon** [comment] 2020-12-31 17:32
<?xml version="1.0" encoding="UTF-8" ?>

<Server version="8">
        <Name>OvenMediaEngine</Name>
        
        <Type>origin</Type>
        
        <IP>*</IP>

        
        <Bind>
                
                

                <Providers>
                        <RTMP>
                                <Port>1935</Port>
                        </RTMP>
                        <MPEGTS>
                                
                                <Port>4000-4004,4005/udp</Port>
                        </MPEGTS>
                </Providers>

                <Publishers>
                        <OVT>
                                <Port>9000</Port>
                        </OVT>
                        <HLS>
                                <Port>8080</Port>
                                
                                
                        </HLS>
                        <DASH>
                                <Port>8080</Port>
                                
                                
                        </DASH>
                        <WebRTC>
                                <Signalling>
                                        <Port>3333</Port>
                                        
                                        
                                </Signalling>
                                <IceCandidates>
                                        <IceCandidate>*:10000-10005/udp</IceCandidate>
                                </IceCandidates>
                        </WebRTC>
                </Publishers>
        </Bind>

        
        

        
        

        <VirtualHosts>
                
                <VirtualHost include="VHost*.xml" />
                <VirtualHost>
                        <Name>default</Name>

                        
                        <Host>
                                <Names>
                                        
                                        <Name>*</Name>
                                </Names>
                                
                        </Host>

                        


                        <Origins>

                                <Origin>
                                        <Location>/vod/CRBD-2401_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.12:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                <Origin>
                                        <Location>/vod/CRBD-2406_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.13:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                <Origin>
                                        <Location>/vod/CRBD-2501_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.14:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                <Origin>
                                        <Location>/vod/CRBD-2506_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.15:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                <Origin>
                                        <Location>/vod/CRBD-2601_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.16:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                <Origin>
                                        <Location>/vod/CRBD-2602_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.17:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                <Origin>
                                        <Location>/vod/CRBD-2605_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.18:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                <Origin>
                                        <Location>/vod/CRBD-3201_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.2:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                                                <Origin>
                                        <Location>/vod/CRBD-3202_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.3:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                <Origin>
                                        <Location>/vod/CRBD-3206_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                
                                                <Urls><Url>admin:888888@10.10.40.4:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                <Origin>
                                        <Location>/vod/CRBD-3207_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.5:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                <Origin>
                                        <Location>/vod/CRBD-3214_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.6:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                                                <Origin>
                                        <Location>/vod/CRBD-3215_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.7:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                <Origin>
                                        <Location>/vod/CRBD-3506_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.8:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                <Origin>
                                        <Location>/vod/CRBD-3507_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.9:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                <Origin>
                                        <Location>/vod/CRBD-3510_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.10:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                                <Origin>
                                        <Location>/vod/CRBD-3511_cam_o</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>admin:888888@10.10.40.11:10554/tcp/av0_0</Url></Urls>
                                        </Pass>
                                </Origin>
                        </Origins>

                        
                        <Applications>
                                <Application>
                                        <Name>vod</Name>
                                        
                                        <Type>live</Type>
                                        <OutputProfiles>
                                                <OutputProfile>
                                                        <Name>bypass_stream</Name>
                                                        <OutputStreamName>${OriginStreamName}</OutputStreamName>
                                                        <Encodes>
                                                                <Audio>
                                                                        <Bypass>true</Bypass>
                                                                </Audio>
                                                                <Video>
                                                                        <Bypass>true</Bypass>
                                                                </Video>
                                                                
                                                        </Encodes>
                                                </OutputProfile>
                                        </OutputProfiles>
                                        <Providers>

                                                <RTMP />
                                                <MPEGTS>
                                                        <StreamMap>
                                                                
                                                                <Stream>
                                                                        <Name>stream_${Port}</Name>
                                                                        <Port>4000,4001-4004</Port>
                                                                </Stream>
                                                                <Stream>
                                                                        <Name>stream_4005</Name>
                                                                        <Port>4005</Port>
                                                                </Stream>
                                                        </StreamMap>
                                                </MPEGTS>
                                                <RTSPPull />
                                        </Providers>
                                        <Publishers>
                                                <SessionLoadBalancingThreadCount>8</SessionLoadBalancingThreadCount>
                                                <OVT />
                                                <WebRTC>
                                                        <Timeout>30000</Timeout>
                                                </WebRTC>
                                                <HLS>
                                                        <SegmentDuration>5</SegmentDuration>
                                                        <SegmentCount>3</SegmentCount>
                                                        <CrossDomains>
                                                                <Url>*</Url>
                                                        </CrossDomains>
                                                </HLS>
                                        </Publishers>
                                </Application>
                        </Applications>
                </VirtualHost>
        </VirtualHosts>
</Server>

[2021-01-01 00:29:47.204] I 61563 Signalling | rtc_signalling_server.cpp:237  | Client is disconnected: <WebSocketClient: 0x7f1d18415040, <ClientSocket: 0x7f1d18401010, #4, state: 4, TCP, 192.168.10.28:52574>> (#default#vod / CRBD-3214_cam_o, ufrag: local: (N/A), remote: (N/A))
[2021-01-01 00:29:49.570] I 61563 Signalling | rtc_signalling_server.cpp:99   | New client is connected: <ClientSocket: 0x7f1d18401010, #4, state: 4, TCP, 192.168.20.125:54966>
[2021-01-01 00:29:49.581] I 61563 Orchestrator | orchestrator.cpp:1280 | Trying to pull stream [#default#vod/CRBD-3214_cam_o] from provider using origin map: PullProvider
[2021-01-01 00:29:49.583] E 61563 OvtStream | ovt_stream.cpp:250  | Describe : Server Failure : 404 (There is no such stream (#default#vod/CRBD-3214_cam_o))
[2021-01-01 00:29:49.583] E 61563 Provider | provider.cpp:149  | Cannot create CRBD-3214_cam_o stream.
[2021-01-01 00:29:49.583] E 61563 Orchestrator | orchestrator.cpp:1319 | Could not pull stream [#default#vod/CRBD-3214_cam_o] from provider: PullProvider
[2021-01-01 00:29:49.583] E 61563 Signalling | rtc_signalling_server.cpp:190  | Cannot find stream [#default#vod/CRBD-3214_cam_o]
[2021-01-01 00:29:49.583] I 61563 Signalling | rtc_signalling_server.cpp:237  | Client is disconnected: <WebSocketClient: 0x7f1d18415010, <ClientSocket: 0x7f1d18401010, #4, state: 4, TCP, 192.168.20.125:54966>> (#default#vod / CRBD-3214_cam_o, ufrag: local: (N/A), remote: (N/A))
[2021-01-01 00:29:50.226] I 61563 Signalling | rtc_signalling_server.cpp:99   | New client is connected: <ClientSocket: 0x7f1d18401010, #4, state: 4, TCP, 192.168.10.28:52577>
[2021-01-01 00:29:50.229] I 61563 Orchestrator | orchestrator.cpp:1280 | Trying to pull stream [#default#vod/CRBD-3214_cam_o] from provider using origin map: PullProvider
[2021-01-01 00:29:50.231] E 61563 OvtStream | ovt_stream.cpp:250  | Describe : Server Failure : 404 (There is no such stream (#default#vod/CRBD-3214_cam_o))
[2021-01-01 00:29:50.232] E 61563 Provider | provider.cpp:149  | Cannot create CRBD-3214_cam_o stream.
[2021-01-01 00:29:50.232] E 61563 Orchestrator | orchestrator.cpp:1319 | Could not pull stream [#default#vod/CRBD-3214_cam_o] from provider: PullProvider
[2021-01-01 00:29:50.232] E 61563 Signalling | rtc_signalling_server.cpp:190  | Cannot find stream [#default#vod/CRBD-3214_cam_o]
[2021-01-01 00:29:50.232] I 61563 Signalling | rtc_signalling_server.cpp:237  | Client is disconnected: <WebSocketClient: 0x7f1d18415160, <ClientSocket: 0x7f1d18401010, #4, state: 4, TCP, 192.168.10.28:52577>> (#default#vod / CRBD-3214_cam_o, ufrag: local: (N/A), remote: (N/A))

**Comment by veraphon** [comment] 2020-12-31 17:33
<?xml version="1.0" encoding="UTF-8" ?>

<Server version="7">
        <Name>OvenMediaEngine</Name>
        
        <Type>edge</Type>
        
        <IP>*</IP>

        
        <Bind>
                <Providers>
                        <RTMP>
                                <Port>1935</Port>
                        </RTMP>
                        <MPEGTS>
                                
                                <Port>4000-4004,4005/udp</Port>
                        </MPEGTS>
                </Providers>

                <Publishers>
                        <OVT>
                                <Port>9000</Port>
                        </OVT>
                        <HLS>
                                <Port>8080</Port>
                                
                                
                        </HLS>
                        <DASH>
                                <Port>8080</Port>
                                
                                
                        </DASH>
                        <WebRTC>
                                <Signalling>
                                        <Port>3333</Port>
                                        
                                        
                                </Signalling>
                                <IceCandidates>
                                        <IceCandidate>*:10000-10005/udp</IceCandidate>
                                </IceCandidates>
                        </WebRTC>
                </Publishers>
        </Bind>

        
        

        <VirtualHosts>
                
                <VirtualHost include="VHost*.xml" />
                <VirtualHost>
                        <Name>default</Name>

                        
                        <Domain>
                                <Names>
                                        
                                        <Name>*</Name>
                                </Names>
                                
                        </Domain>

                        <Origins>

                                <Origin>
                                        <Location>/vod/CRBD-3214_cam_o</Location>
                                        <Pass>
                                                <Scheme>ovt</Scheme>
                                                <Urls><Url>10.10.11.39:9000/vod/CRBD-3214_cam_o</Url></Urls>
                                        </Pass>
                                </Origin>

                        </Origins>

                        
                        <Applications>
                                <Application>
                                        <Name>vod</Name>
                                        
                                        <Type>live</Type>
                                        <Providers>
                                        <OVT />
                                        </Providers>

                                        <Publishers>
                                                <ThreadCount>24</ThreadCount>
                                                <OVT />
                                                <WebRTC>
                                                        <Timeout>30000</Timeout>
                                                </WebRTC>
                                                <HLS>
                                                        <SegmentDuration>5</SegmentDuration>
                                                        <SegmentCount>3</SegmentCount>
                                                        <CrossDomain>
                                                                <Url>*</Url>
                                                        </CrossDomain>
                                                </HLS>
                                        </Publishers>
                                </Application>
                        </Applications>
                </VirtualHost>
        </VirtualHosts>
</Server>
[2021-01-01 00:29:40.594] I [PhyPortSerSock:35408] OVT | ovt_publisher.cpp:94   | OvtProvider is connected : <ClientSocket: 0x7f74c8000b90, #37, state: 4, TCP, 10.10.11.54:59144>
[2021-01-01 00:29:40.595] E [PhyPortWorker:35405] Orchestrator | orchestrator.cpp:448  | Pull stream is requested for invalid URL: CRBD-3214_cam_o
[2021-01-01 00:29:41.215] I [PhyPortSerSock:35408] OVT | ovt_publisher.cpp:94   | OvtProvider is connected : <ClientSocket: 0x7f74c8000b90, #37, state: 4, TCP, 10.10.11.54:59146>
[2021-01-01 00:29:41.216] E [PhyPortWorker:35405] Orchestrator | orchestrator.cpp:448  | Pull stream is requested for invalid URL: CRBD-3214_cam_o
[2021-01-01 00:29:43.594] I [PhyPortSerSock:35408] OVT | ovt_publisher.cpp:94   | OvtProvider is connected : <ClientSocket: 0x7f74c8000b90, #37, state: 4, TCP, 10.10.11.54:59150>
[2021-01-01 00:29:43.594] E [PhyPortWorker:35405] Orchestrator | orchestrator.cpp:448  | Pull stream is requested for invalid URL: CRBD-3214_cam_o
[2021-01-01 00:29:44.225] I [PhyPortSerSock:35408] OVT | ovt_publisher.cpp:94   | OvtProvider is connected : <ClientSocket: 0x7f74c8000b90, #37, state: 4, TCP, 10.10.11.54:59152>
[2021-01-01 00:29:44.226] E [PhyPortWorker:35405] Orchestrator | orchestrator.cpp:448  | Pull stream is requested for invalid URL: CRBD-3214_cam_o
[2021-01-01 00:29:46.621] I [PhyPortSerSock:35408] OVT | ovt_publisher.cpp:94   | OvtProvider is connected : <ClientSocket: 0x7f74c8000b90, #37, state: 4, TCP, 10.10.11.54:59156>
[2021-01-01 00:29:46.622] E [PhyPortWorker:35405] Orchestrator | orchestrator.cpp:448  | Pull stream is requested for invalid URL: CRBD-3214_cam_o
[2021-01-01 00:29:47.210] I [PhyPortSerSock:35408] OVT | ovt_publisher.cpp:94   | OvtProvider is connected : <ClientSocket: 0x7f74c8000b90, #37, state: 4, TCP, 10.10.11.54:59158>
[2021-01-01 00:29:47.210] E [PhyPortWorker:35405] Orchestrator | orchestrator.cpp:448  | Pull stream is requested for invalid URL: CRBD-3214_cam_o
[2021-01-01 00:29:49.589] I [PhyPortSerSock:35408] OVT | ovt_publisher.cpp:94   | OvtProvider is connected : <ClientSocket: 0x7f74c8000b90, #37, state: 4, TCP, 10.10.11.54:59162>
[2021-01-01 00:29:49.589] E [PhyPortWorker:35405] Orchestrator | orchestrator.cpp:448  | Pull stream is requested for invalid URL: CRBD-3214_cam_o

**Comment by veraphon** [comment] 2020-12-31 17:36
if client view webrtc on origin and ovt work

see origin log
[2021-01-01 00:34:35.298] I [PhyPortWorker:35369] Transcoder | transcode_stream.cpp:524  | [#default#vod/CRBD-3214_cam_o(100)] -> [#default#vod/CRBD-3214_cam_o(219680726)] Output stream has been created.
[2021-01-01 00:34:35.298] I [PhyPortWorker:35369] Transcoder | transcode_stream.cpp:109  | No decoder generated
[2021-01-01 00:34:35.298] I [PhyPortWorker:35369] MediaRouter | mediarouter_application.cpp:245  | Trying to create a stream: [#default#vod/CRBD-3214_cam_o(219680726)]
[2021-01-01 00:34:35.298] I [PhyPortWorker:35369] MediaRouter | mediarouter_application.cpp:246  |
[Stream Info]
id(219680726), output(CRBD-3214_cam_o), SourceType(Transcoder), Created Time (Fri Jan  1 00:34:35 2021)
        >> Origin Stream Info
        id(100), output(CRBD-3214_cam_o), SourceType(RtspPull), Created Time (Fri Jan  1 00:34:33 2021)

        Video Track #0: Bypass(true) Bitrate(0b) codec(1, H264) resolution(1920x1080) framerate(10.00fps) timebase(1/90000)
[2021-01-01 00:34:35.298] I [PhyPortWorker:35369] MediaRouter | mediarouter_stream.cpp:54   | Trying to create media route stream: name(CRBD-3214_cam_o) id(219680726)
[2021-01-01 00:34:35.298] I [PhyPortWorker:35369] Monitor | application_metrics.cpp:56   | Create StreamMetrics(CRBD-3214_cam_o) for monitoring
[2021-01-01 00:34:35.298] I [PhyPortWorker:35369] Publisher | stream.cpp:181  | WebRTC Publisher Application application has started [CRBD-3214_cam_o(219680726)] stream
[2021-01-01 00:34:35.298] I [PhyPortWorker:35369] Publisher | stream.cpp:181  | HLS Publisher Application application has started [CRBD-3214_cam_o(219680726)] stream
[2021-01-01 00:34:35.298] I [PhyPortWorker:35369] Publisher | stream.cpp:181  | OVTPublisher Application application has started [CRBD-3214_cam_o(219680726)] stream
[2021-01-01 00:34:35.299] I [PhyPortWorker:35369] Transcoder | transcode_stream.cpp:121  | [#default#vod/CRBD-3214_cam_o(100)] Transcoder input stream has been started. Status : (0) Decoders, (0) Encoders
[2021-01-01 00:34:35.299] I [PhyPortWorker:35369] Provider | stream.cpp:36   | RTSPCProvider Application has started to play [CRBD-3214_cam_o(100)] stream
[2021-01-01 00:34:35.299] I [PhyPortWorker:35369] Provider | stream_motor.cpp:131  | #default#vod/CRBD-3214_cam_o(100) stream has added to 0 StreamMotor
[2021-01-01 00:34:35.299] I [PhyPortWorker:35369] Orchestrator | orchestrator.cpp:574  | The stream was pulled successfully: [#default#vod/CRBD-3214_cam_o] (100)
[2021-01-01 00:34:35.299] I [PhyPortWorker:35369] WebRTC | webrtc_publisher.cpp:332  | URL rtsp://admin:888888 is requested
[2021-01-01 00:34:35.599] I [PhyPortSerSock:35408] OVT | ovt_publisher.cpp:94   | OvtProvider is connected : <ClientSocket: 0x7f74c8000b90, #42, state: 4, TCP, 10.10.11.54:59746>
[2021-01-01 00:34:35.725] I [PhyPortWorker:35369] Monitor | stream_metrics.cpp:119  | A new session has started playing #default#vod/CRBD-3214_cam_o on the WebRTC publihser. WebRTC(1)/Stream total(1)/App total(1)
[2021-01-01 00:34:50.808] I [AppWorker:35428] HLS | hls_packetizer.cpp:390  | [#default#vod/CRBD-3214_cam_o] HLS: Segments are ready, segment duration: 5.000000s, count: 3

**Comment by veraphon** [comment] 2020-12-31 17:36
if client view webrtc on origin and ovt work

see edge log

[2021-01-01 00:34:35.224] E 61563 Orchestrator | orchestrator.cpp:1319 | Could not pull stream [#default#vod/CRBD-3214_cam_o] from provider: PullProvider
[2021-01-01 00:34:35.224] E 61563 Signalling | rtc_signalling_server.cpp:190  | Cannot find stream [#default#vod/CRBD-3214_cam_o]
[2021-01-01 00:34:35.224] I 61563 Signalling | rtc_signalling_server.cpp:237  | Client is disconnected: <WebSocketClient: 0x7f1d18416300, <ClientSocket: 0x7f1d18401290, #4, state: 4, TCP, 192.168.10.28:52920>> (#default#vod / CRBD-3214_cam_o, ufrag: local: (N/A), remote: (N/A))
[2021-01-01 00:34:35.584] I 61563 Signalling | rtc_signalling_server.cpp:99   | New client is connected: <ClientSocket: 0x7f1d18401010, #4, state: 4, TCP, 192.168.20.125:55347>
[2021-01-01 00:34:35.594] I 61563 Orchestrator | orchestrator.cpp:1280 | Trying to pull stream [#default#vod/CRBD-3214_cam_o] from provider using origin map: PullProvider
[2021-01-01 00:34:35.596] I 61563 Provider | stream.cpp:49   | #default#vod/CRBD-3214_cam_o(336) has been started stream
[2021-01-01 00:34:35.596] I 61563 Provider | application.cpp:116  | #default#vod application has created 6 stream motor
[2021-01-01 00:34:35.596] I 61563 MediaRouter.App | media_router_application.cpp:205  | Trying to create a stream: [#default#vod/CRBD-3214_cam_o(336)]
[2021-01-01 00:34:35.596] I 61563 Monitor | stream.cpp:254  |
[Stream Info]
id(336), name(CRBD-3214_cam_o), SourceType(Ovt), Created Time (Fri Jan  1 00:34:35 2021)

        Video Track #0: Bypass(false) Bitrate(0b) codec(1, avc) resolution(1920x1080) framerate(10.00fps) timebase(1/90000)
[2021-01-01 00:34:35.596] I 61563 Monitor | application_metrics.cpp:56   | Create StreamMetrics(CRBD-3214_cam_o) for monitoring
[2021-01-01 00:34:35.597] I 61563 Publisher | stream.cpp:211  | WebRTC Publisher Application application has started [CRBD-3214_cam_o(336)] stream
[2021-01-01 00:34:35.597] I 61563 Publisher | stream.cpp:211  | HLS Publisher Application application has started [CRBD-3214_cam_o(336)] stream
[2021-01-01 00:34:35.597] I 61563 Publisher | stream.cpp:211  | OVTPublisher Application application has started [CRBD-3214_cam_o(336)] stream
[2021-01-01 00:34:35.598] I 61563 Provider | stream.cpp:36   | OvtProvider Application has started to play [CRBD-3214_cam_o(336)] stream
[2021-01-01 00:34:35.598] I 61563 Provider | stream_motor.cpp:130  | #default#vod/CRBD-3214_cam_o(336) stream has added to 6 StreamMotor
[2021-01-01 00:34:35.598] I 61563 Orchestrator | orchestrator.cpp:1302 | The stream was pulled successfully: [#default#vod/CRBD-3214_cam_o] (336)
[2021-01-01 00:34:35.867] I 61563 Monitor | stream_metrics.cpp:119  | A new session has started playing #default#vod/CRBD-3214_cam_o on the WebRTC publihser. WebRTC(1)/Stream total(1)/App total(1)
[2021-01-01 00:34:35.869] W 61563 Socket | socket_address.cpp:277  | An error occurred while resolve DNS for host [c892d58c-c4c9-4cef-9c84-fd8025b8a161.local]
[2021-01-01 00:34:35.869] W 61563 Socket | socket_address.cpp:84   | An error occurred: c892d58c-c4c9-4cef-9c84-fd8025b8a161.local:49673
[2021-01-01 00:34:38.238] I 61572 Signalling | rtc_signalling_server.cpp:99   | New client is connected: <ClientSocket: 0x7f1d18401290, #29, state: 4, TCP, 192.168.10.28:52924>
[2021-01-01 00:34:38.657] I 61572 Monitor | stream_metrics.cpp:119  | A new session has started playing #default#vod/CRBD-3214_cam_o on the WebRTC publihser. WebRTC(2)/Stream total(2)/App total(2)
[2021-01-01 00:34:38.659] W 61572 Socket | socket_address.cpp:277  | An error occurred while resolve DNS for host [be2374b5-34d4-4302-806b-9887e16c20ae.local]
[2021-01-01 00:34:38.659] W 61572 Socket | socket_address.cpp:84   | An error occurred: be2374b5-34d4-4302-806b-9887e16c20ae.local:50381

**Comment by getroot** [comment] 2021-01-02 04:31
Thanks for your detailed information.
It seems that the recently updated code has not been applied to the OVT publisher. I will analyze this, correct it and comment again here.

**Comment by getroot** [comment] 2021-01-08 04:08
This problem has been resolved and committed to the Master branch.
Please let me know if your problem is resolved.

**Comment by getroot** [comment] 2021-01-12 02:44
I have confirmed that this problem has been resolved after several tests. If the problem is reproduced, please reopen this issue.

**Closed by getroot** 2021-01-12 02:44 UTC
Labels: bug
