### ISSUE TITLE
Failed to start recording with WebRTC

### ISSUE THREAD

**Issue by kage212** [AirenSoft/OvenMediaEngine#799] opened 2022-06-20 15:20 UTC
Hello OME team!

**Describe the bug**
When I try to record a WebRTC stream its does not start.

**To Reproduce**
1. Set Server.xml 
``
<?xml version="1.0" encoding="UTF-8"?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	<PrivacyProtection>false</PrivacyProtection>

	
	<StunServer>stun.l.google.com:19302</StunServer>

	<Modules>
		
		<HTTP2>
			<Enable>true</Enable>
		</HTTP2>

		<LLHLS>
			<Enable>true</Enable>
		</LLHLS>

		
		<P2P>
			
			<Enable>false</Enable>
			<MaxClientPeersPerHostPeer>2</MaxClientPeersPerHostPeer>
		</P2P>
	</Modules>

<Bind>
	
	<Managers>
		<API>
			<Port>${env:OME_API_PORT:8081}</Port>
			<TLSPort>${env:OME_API_TLSPORT:8082}</TLSPort>
			<WorkerCount>1</WorkerCount>
		</API>
	</Managers>

	<Providers>
		
		<RTSPC>
			<WorkerCount>1</WorkerCount>
		</RTSPC>
		<OVT>
			<WorkerCount>1</WorkerCount>
		</OVT>
		
		<RTMP>
				<Port>${env:OME_RTMP_PROV_PORT:1960}</Port>
			<WorkerCount>1</WorkerCount>
		</RTMP>
		<SRT>
			<Port>${env:OME_SRT_PROV_PORT:9999}</Port>
			<WorkerCount>1</WorkerCount>
		</SRT>
		<MPEGTS>
			
			<Port>${env:OME_MPEGTS_PROV_PORT:4000/udp}</Port>
		</MPEGTS>
		<WebRTC>
			<Signalling>
				<Port>3333</Port>
				<TLSPort>3334</TLSPort>
				<WorkerCount>1</WorkerCount>
			</Signalling>

			<IceCandidates>
				<IceCandidate>${env:OME_ICE_CANDIDATES:*:10000-10005/udp}</IceCandidate>
				
				<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
				
				<TcpForce>true</TcpForce>
				<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
			</IceCandidates>
		</WebRTC>
	</Providers>

	<Publishers>
		<OVT>
			<Port>${env:OME_ORIGIN_PORT:9000}</Port>
			<WorkerCount>1</WorkerCount>
		</OVT>
		<LLHLS>
			
			<Port>3333</Port>
			
			<TLSPort>3334</TLSPort>
			<WorkerCount>1</WorkerCount>
		</LLHLS>
		<WebRTC>
			<Signalling>
				<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
				<TLSPort>3334</TLSPort>
				<WorkerCount>1</WorkerCount>
			</Signalling>
			<IceCandidates>
				<IceCandidate>${env:OME_ICE_CANDIDATES:*:10000-10005/udp}</IceCandidate>
				
				<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
				
				<TcpForce>true</TcpForce>
				<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
			</IceCandidates>
		</WebRTC>
	</Publishers>
</Bind>

	
	<Managers>
		<Host>
			<Names>
				<Name>*</Name>
			</Names>
			
		</Host>
		<API>
			<AccessToken>${env:OME_ACCESS_TOKEN}</AccessToken>
		</API>
	</Managers>

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			
			<Distribution>ovenmediaengine.com</Distribution>

			
			<Host>
				<Names>
					
					<Name>*</Name>
				</Names>
				<TLS>
					<CertPath>ssl/x.cert.crt</CertPath>
					<KeyPath>ssl/x.key</KeyPath>
					<ChainCertPath>ssl/x.chain.crt</ChainCertPath>
				</TLS>
			</Host>

			<AdmissionWebhooks>
				<ControlServerUrl>https://backend:xxxx/api/</ControlServerUrl>
				<SecretKey>${env:OME_SECRET}</SecretKey>
				<Timeout>3000</Timeout>
				<Enables>
					<Providers>rtmp,webrtc,srt</Providers>
					<Publishers>webrtc,hls,llhls,dash,lldash</Publishers>
				</Enables>
			</AdmissionWebhooks>

			
			
			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						
						<HardwareAcceleration>false</HardwareAcceleration>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>

							

							<Encodes>
								<Audio>
									<Name>bypass_audio</Name>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Name>bypass_video</Name>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
								
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
						<RTSPPull />
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
					</Providers>
					<Publishers>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						<LLHLS>
							<ChunkDuration>0.5</ChunkDuration>
							<SegmentDuration>6</SegmentDuration>
							<SegmentCount>10</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</LLHLS>
						<FILE>
							<RootPath>${env:OME_RECORD_PATH}</RootPath>
							<FilePath>/${VirtualHost}/${Application}/${Stream}/${StartTime:YYYYMMDDhhmmss}_${EndTime:YYYYMMDDhhmmss}.ts</FilePath>
							<InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
						</FILE>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>
``
2. Then a POST request like this 'domain/v1/vhosts/default/apps/app:startRecord'.
{
      'id': key,
      'stream': { 'name': uid, 'tracks': [100, 200] },
      'filePath': `${key}` + '/file_${Sequence}.ts',
      'infoPath': `${key}/file.xml`,
      'interval': 60000,
      'segmentationRule': 'continuity',
}

3. Using OvenLiveKit to stream

**Expected behavior**
A recorded stream.

**Logs**
[log.txt](https://github.com/AirenSoft/OvenMediaEngine/files/8941768/log.txt)

Important parts:
[2022-06-20 15:07:36.018] W [SPRtcSig-T3334:13] Transcoder | transcoder_stream.cpp:425  | OPUS codec only supports 48000Hz samplerate. Do not create bypass track
[2022-06-20 15:07:36.018] W [SPRtcSig-T3334:13] Transcoder | transcoder_stream.cpp:545  | Encoding codec set is not a audio codec, track_id(-807287834)
[2022-06-20 15:07:36.554] I [OutboundWorker:36] Publisher | stream.cpp:202  | WebRTC Publisher Application application has started [67ZyaYHkxY(3843573246)] stream (MSID : 0)
[2022-06-20 15:07:36.555] I [OutboundWorker:36] LLHLS Publisher | llhls_stream.cpp:81   | LLHlsStream(#default#app/67ZyaYHkxY) - Ignore unsupported codec(OPUS)
[2022-06-20 15:07:36.557] E [OutboundWorker:36] FFmpeg | third_parties.cpp:111  | [AVFormatContext: 0x7fc6f80057c0] No streams to mux were specified
[2022-06-20 15:07:36.557] I [OutboundWorker:36] Publisher | stream.cpp:202  | FilePublisher Application application has started [67ZyaYHkxY(3843573246)] stream (MSID : 0)
[2022-06-20 15:07:36.557] E [OutboundWorker:36] FILE | file_session.cpp:47   | Failed to start recording. id(100)

**Server (please complete the following information):**
 - OvenMediaEngine Version: 14.2
 - Branch: release

Thanks for your time

**Comment by Keukhan** [comment] 2022-06-23 08:28
@kage212 

The cause of the problem is that you tried to record a track that did not exist. In conclusion, this is a situation that occurs when there is no track to be saved.

> Origin Stream Info
	id(100), output(67ZyaYHkxY), SourceType(WebRTC), Created Time (Mon Jun 20 15:06:09 2022)
	Audio Track #1: Bypass(false) Bitrate(128.00Kb) codec(8, OPUS) samplerate(48.0K) format(none, 0) channel(stereo, 2) timebase(1/48000)
	Video Track #2: Bypass(true) Bitrate(96.90Kb) codec(1, H264) resolution(640x360) framerate(10.49fps) timebase(1/90000)


Tracks of the output stream(67ZyaYHkxY) can be identified as #1(Audio) and #2(Video). However, it was requested as `'tracks': [100, 200] } `in startRecord.
To solve the problem, remove the `tracks `tag and try to record the all track, or put the correct track id in the `tracks`.

Thanks

**Comment by kage212** [comment] 2022-06-27 08:47
You're right!
Thanks

**Comment by getroot** [comment] 2022-06-27 12:07
If your issue is resolved, please close this issue.

**Closed as completed** 2022-06-27 13:46 UTC
Labels: bug
