### ISSUE TITLE
SignedPolicy not working

### ISSUE THREAD

**Issue by tjsas1** [AirenSoft/OvenMediaEngine#252] opened 2021-01-12 19:46 UTC
Enabled the feature on the config using

<code>
&lt;SignedPolicy&gt;
&lt;PolicyQueryKeyName&gt;policy&lt;/PolicyQueryKeyName&gt;
&lt;SignatureQueryKeyName&gt;signature&lt;/SignatureQueryKeyName&gt;
&lt;SecretKey&gt;1k8DD#&lt;/SecretKey&gt;
&lt;Enables&gt;
	&lt;Providers&gt;rtmp&lt;/Providers&gt;
	&lt;Publishers&gt;webrtc&lt;/Publishers&gt;
&lt;/Enables&gt;
&lt;/SignedPolicy&gt;
</code>

Create a SignedPolicy url via signed_policy_url_generator.sh

RTMP won't push thru on OBS. Always saying please check stream key.

**Comment by getroot** [comment] 2021-01-13 01:38
You have to tell me how you used signed_policy_url_generator.sh so I know what's wrong.

**Comment by getroot** [comment] 2021-01-13 01:48
Please tell me how you used it, as in the manual below.
https://airensoft.gitbook.io/ovenmediaengine/signedpolicy#usage-examples

**Comment by tjsas1** [comment] 2021-01-13 06:59
I've used it with

./s.sh key rtmp://xx.xx.xx.xx:1935/app/ch1 signature policy {"url_activate":1611072000000,"url_expire":1611072000000,"stream_expire":1611072000000}

**Comment by getroot** [comment] 2021-01-13 07:16
You have to put "1k8DD#" instead of "key" in "./s.sh key ~~". Did you do that?
How did you set it up for OBS?

Upload your Server.xml and ovenmediaengine.log. I need more information.

**Comment by tjsas1** [comment] 2021-01-13 07:32
Yes I did that. But I found the issue already the policy needs to be enclosed with single quote but will only work with only 1 policy is defined. 

<code>
./s.sh key rtmp://xx.xx.xx.xx:1935/app/ch1 signature policy '{"url_expire":1611072000000}'
</code>

But having problem now if the policy is like this

<code>
./s.sh key rtmp://xx.xx.xx.xx:1935/app/ch1 signature policy '{"url_activate":1611072000000,"url_expire":1611072000000,"stream_expire":1611072000000}'
</code>

OME crash after trying the link generated. See attached dump

[crash_20210113.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5807051/crash_20210113.txt)

**Comment by tjsas1** [comment] 2021-01-13 07:34
Also it needs to point that the URL generated include a space on the policy value.

**Comment by getroot** [comment] 2021-01-13 07:52
Ok, thanks for your bug report.
I will look into this soon.

**Comment by getroot** [comment] 2021-01-13 09:22
I patched and committed this issue to the master branch. Could you please check again?

**Comment by tjsas1** [comment] 2021-01-13 09:38
Its working now but I think the policy allow_ip is not working as its crashing OME.

See attached dump
[crash_20210113.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5807681/crash_20210113.txt)

**Comment by tjsas1** [comment] 2021-01-13 09:38
Sample policy

'{"url_expire":1611072000000,"allow_ip":"110.54.159.100/32"}'

**Comment by getroot** [comment] 2021-01-13 13:02
In fact, allow_ip was not implemented.
I have implemented and committed it while I saw your report.
Could you check if it works well?

**Comment by tjsas1** [comment] 2021-01-13 18:37
How can I build and run on the latest code every time there is a new code?

**Comment by getroot** [comment] 2021-01-14 14:37
Just git pull and make release, make install. Detecting new code and automatically building it can be done easily with tools like jenkins.

**Comment by getroot** [comment] 2021-01-18 08:19
I have confirmed that this problem has been resolved.
If the problem is reproduced, please reopen this issue.

**Closed by getroot** 2021-01-18 08:19 UTC
Labels: bug
