### ISSUE TITLE
Could not find binding request info : transaction id

### ISSUE THREAD

**Issue by DScrp** [AirenSoft/OvenMediaEngine#402] opened 2021-06-02 15:09 UTC
Hello.
I broadcast from three cameras by ffmpeg. Sometimes it works without problems. Sometimes an error appears in the logs:
```
[2021-06-02 17:49:06.491] W [SPICE:15726] Ice | ice_port.cpp:855  | Could not find binding request info : transaction id(j6dTtEjuwuFZ)
[2021-06-02 17:49:06.491] W [SPICE:15726] Ice | ice_port.cpp:855  | Could not find binding request info : transaction id(ATVzTtkoLNxj)
[2021-06-02 17:49:06.491] W [SPICE:15726] Ice | stun_message.cpp:147  | Message is too short: 36 (expected: 116)
[2021-06-02 17:49:06.491] W [SPICE:15726] Ice | ice_port.cpp:855  | Could not find binding request info : transaction id(7MdshHHONsqE)
[2021-06-02 17:49:06.491] W [SPICE:15726] Ice | ice_port.cpp:855  | Could not find binding request info : transaction id(6Z80ULYco3cF)
[2021-06-02 17:49:06.491] W [SPICE:15726] Ice | ice_port.cpp:855  | Could not find binding request info : transaction id(vM4GhzxoJYe1)
[2021-06-02 17:49:06.491] W [SPICE:15726] Ice | ice_port.cpp:855  | Could not find binding request info : transaction id(puNDkDPplYpD)
```

Errors appear in large numbers. They load the CPU by 100%. They only stop after restart ovenMediaEngine service. I only use RTMP provider and webRTC publisher (transport=tcp). 
What is the reason and how to fix it?

OvenMediaEngine v0.12.0
Debian 10.9
OvenMediaEngine config: [Server.xml](https://github.com/AirenSoft/OvenMediaEngine/files/6585517/Server.txt)

**Comment by getroot** [comment] 2021-06-04 10:46
This seems to be the case where the problem occurred because the CPU was 100%. (The problem is not making the CPU load 100%, but the opposite.) What happens at that time? (Is the player connection forcibly terminated?)

You are using 3 applications. How many streams and how many concurrent users are there? What are your hardware specs?

You can try something like this:
- Try reducing <SessionLoadBalancingThreadCount>8.
- Try closing <Rtx>true</Rtx> with false.
- Opus encoding also uses more CPU than expected.
- Try using only one application and multiple streams.

**Comment by DScrp** [comment] 2021-06-04 11:32
systemd-journald loads the CPU to 100%. Because system logs are increasing at a high rate. OvenMediaEngine at this moment does not load the CPU. At this time, the video starts freezing, latency increase. 
Problem happens when I open two or three tabs with players in one browser. And I switch between them. If after problem all players are closed, the load will not decrease. Errors in logs continues.

I have 2 streams in any application. There are 3*2=6 streams in total.
I have dedicated server, Intel Xeon E5-2620v3 2.4/3.2GHz, 6/12, 32GB DDR4. This is a powerful server, it won't have a problem to encode 6 audio-streams.

"Try reducing 8", "Try closing true with false." - Explain, please, what does this mean?
"Opus encoding also uses more CPU than expected." - As I wrote, there is no load CPU.
"Try using only one application and multiple streams." - How does one app and 6 streams differ from 3 apps with 2 streams?

**Comment by getroot** [comment] 2021-06-04 11:48
> systemd-journald loads the CPU to 100%. Because system logs are increasing at a high rate. 

What are the logs? Please upload it.

"Try reducing 8" was displayed incorrectly because the markup string was not output. I fixed it.

Application creates multiple threads. On the inside, many things are different.

Anyway your CPU is powerful enough to handle 6 stream inputs so it should work. So there is no need to try to reduce the CPU load I suggested.

To solve this I need to find out why your CPU is being loaded at 100%. Is there any other information I should know? For example, your encoder's bitrate value or other information.

**Comment by getroot** [comment] 2021-06-04 11:52
```
[2021-06-02 17:49:06.491] W [SPICE:15726] Ice | ice_port.cpp:855  | Could not find binding request info : transaction id(j6dTtEjuwuFZ)
```

> Errors appear in large numbers. They load the CPU by 100%. They only stop after restart ovenMediaEngine service. I only use RTMP provider and webRTC publisher (transport=tcp).

Oh, you meant that the log you posted in the first post was massively printed. Does it continue to output even if I close the player connection? This seems to be a bug that occurs under some circumstances. But I haven't experienced this yet. Is there any way you know of to reproduce this problem?

**Comment by DScrp** [comment] 2021-06-04 12:07
> What are the logs? Please upload it.

I gave the example above. Logs are filled with messages " W [SPICE:15726] Ice | ice_port.cpp:855  | Could not find binding request info : transaction id"
All OvenMediaEngine logs go to the syslog. Logs write in huge numbers, many times per second. And systemd-journald loads the CPU to 100%

> Oh, you meant that the log you posted in the first post was massively printed. 
Yes.

> Does it continue to output even if you close the player connection? 
Sometimes logs continue, sometimes they don't.

> Is there any way you know of to reproduce this problem? (and what browser do you use?)
Problem happens when I open two or three tabs with players in one browser. And I switch between them. Browser - Google Chrome. I use webRTC with transport=tcp.

**Comment by getroot** [comment] 2021-06-04 12:21
Every time I test the ome, I open multiple tabs to test it, but I haven't seen any issues like this yet.  

How often does this problem occur to you?  

Do you have experience testing on Ubuntu or docker?  

The only difference between you and me is the type of operating system and the use of syslog?  

I'll do some more digging to reproduce this problem.

**Comment by DScrp** [comment] 2021-06-04 12:30
> How often does this problem occur to you?

Whenever I use several tabs with streams and switch between them, pause, etc.

> Do you have experience testing on Ubuntu or docker?
No. I have Debian 10.9.

> The only difference between you and me is the type of operating system and the use of syslog?
In any app i use 2 streams: 1440p (5000 Kbps) and 720p (2000 Kbps). In tests i use only streams with 1440p video.

What causes these errors to appear? Is there a way to fundamentally eliminate them? We are launching the project tomorrow and we need to solve this problem in any way. WebRTC via TCP work fine, latency is very low. But this errors...

**Comment by getroot** [comment] 2021-06-04 13:02
The log means that ome sent a stun request to the browser, but the browser's stun response was not received within 3 seconds.  But it's very curious as only a few players can't generate that much log.  
Anyway, this log is often found when the system is already very slow, the network bandwidth is full, or the memory is low.
Try testing with 1 app and 1 stream to see if the issue is reproduced.  And check if the cpu, network, and memory are all normal.

**Comment by DScrp** [comment] 2021-06-04 13:45
When I open a new tab with video in the browser, latency in the old tab video increases. Over time, it reaches several minutes. At this time, errors are received in the logs.

**Comment by getroot** [comment] 2021-06-04 14:25
Could it be that your pc's network is slow?  (If there are two, 10mbps is required) Could it be a Wi-Fi problem?  From what you say, it may not be a server problem.  How about playing it on mobile or another PC?

**Comment by DScrp** [comment] 2021-06-04 14:30
Network is fast. On other devices same problem. 
How can I remove this errors so that it does not load the processor? If the client has a low speed, then the video should be shown to him with delays. But this should not overload the log with errors, slow down the system and loads the CPU to 100%.

**Comment by getroot** [comment] 2021-06-04 14:35
Change Ice log level to critical in Logger.xml

**Comment by DScrp** [comment] 2021-06-04 14:39
How can i do it? My Logger.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<Logger version="2">
	<!-- Log file location -->
	<Path>/var/log/ovenmediaengine</Path>

	<!-- Disable some SRT internal logs -->
	<Tag name="SRT" level="critical" />
	<Tag name="HttpServer" level="warn" />
	<Tag name=".*\.Stat" level="warn" />

	<!-- Log level: [debug, info, warn, error, critical] -->
	<Tag name=".*" level="info" />
</Logger>
```

**Comment by getroot** [comment] 2021-06-07 01:34
<Tag name="Ice" level="critical" /> will work in your case. But I don't think this will ultimately solve your problem.

First, the process of outputting the log (Could not find bidning...) is as follows.

1. Chrome first sends a STUN request to OME.
2. OME sends STUN response to Chrome and immediately sends STUN request.
3. Chrome sends a STUN response.
4. OME processes the STUN response sent by Chrome in step 3. At this time, if the response does not reach OME within 3 seconds, the transaction is deleted. If a response comes after deletion, your log is output. (Could not find binding request info)

That is, the "Could not find binding request info ~" log is output only when Chrome first sends a STUN request in step 1. Chrome usually sends once every few seconds, and at most sends 2 or 3 STUN requests per second. Therefore, if the log is output a lot, something is wrong. And it's almost impossible for the log to use 100% of the CPU.

So I think the problem is somewhere else. (The log is probably not the problem.) Here are my thoughts on the possibilities. Please upload the entire ovenmediaengine.log file to further analyze the problem.

- The player's network is slow, so the send buffer of OME continues to increase and uses up all the memory (usually, the player is terminated soon, so OME does not delete packets from the buffer)
- File writing is not fast enough (file system may be NFS or various other problems), OME is getting slower due to syslog output, and the recv buffer continues to increase, causing a problem.
- The socket buffer of the kernel is not large enough, so the input/output that one process can handle is small, which causes a problem.  (refer https://access.redhat.com/sites/default/files/attachments/20150325_network_performance_tuning.pdf)
- We don't have experience with debian, so something else in that environment is causing the problem.

The problems I can imagine are the above. Your more accurate analysis is needed. If you find the cause of the problem, we would appreciate it if you could share it for all of us.

Also try testing at http://demo.ovenplayer.com/ome_demo.html. Does this also cause the same problem? (Although this server is located in Seoul/Korea, it may be difficult to test accurately because the bandwidth is only 10Mbps)

**Comment by getroot** [comment] 2021-08-09 02:15
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.

**Closed by getroot** 2021-08-09 02:15 UTC

**Comment by AlexBrod-lab** [comment] 2022-07-24 08:45
Hi getroot,
I constantly face same issue when my player's 4G network is slow, but if and when I switch it to a faster WiFi network then it consumes rtmp stream smoothly and no errors at my OME server are shown. I uses OME as docker.
Seems what you wrote above:

**The player's network is slow, so the send buffer of OME continues to increase and uses up all the memory (usually, the player is terminated soon, so OME does not delete packets from the buffer)**

is being the root problem.

But it's a typical use case when receiver's network is slower than streamer's one. 
So how to resolve it ? Some OME tuning?

Alex.

**Comment by getroot** [comment] 2022-07-25 02:31
@AlexBrod-lab What exactly is your problem? Does OME's memory keep growing?
This is an issue that was solved a long time ago. OME has been around for a long time to solve this problem by disconnecting clients that delay sending a package for more than 10 seconds. This means that when a slow client connects, OME disconnects that client so that the memory doesn't grow any more.

**Comment by AlexBrod-lab** [comment] 2022-07-31 14:36
@getroot 
seems you're right, slow clients are disconnected in most of my trials.
Maybe I faced a different scenario.
Thanks a lot.

**Comment by SabsLive999** [comment] 2022-08-13 14:06
Everytime that there is "**Could not find binding request info**" in the log the player also glitch.
