### ISSUE TITLE
Problem with starting Engine

### ISSUE THREAD

**Issue by davidghukasyan** [AirenSoft/OvenMediaEngine#14] opened 2019-02-11 07:17 UTC
Hi , i got problem with running the server 

below is my ffmpeg version. I am streaming via Nimble Server and attached Server.xml . If you could please help to sole the issue.

![screenshot 191](https://user-images.githubusercontent.com/28674436/52549799-5773c680-2dd5-11e9-8dd6-0c79bbabbea8.png)
. 

ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
configuration: --disable-static --enable-shared --extra-libs=-ldl --enable-ffprobe --disable-ffplay --disable-ffserver --disable-filters --disable-vaapi --disable-avdevice --disable-doc --disable-symver --disable-debug --disable-indevs --disable-outdevs --disable-devices --disable-hwaccels --disable-encoders --enable-zlib --enable-libopus --enable-libvpx --enable-libfdk_aac --enable-encoder='libvpx_vp8,libvpx_vp9,libopus,libfdk_aac' --disable-decoder=tiff --enable-filter='asetnsamples,aresample,aformat,channelmap,channelsplit,scale,transpose,fps,settb,asettb'
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavfilter     6.107.100 /  6.107.100
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100

**Comment by sfreet** [comment] 2019-02-11 11:45
Hello davidghukasyan~

Thank you for registering issue.
I succeeded in reproducing the problem based on your comments.
It seems to be a compatibility issue with nimble streamer, but it may take several days to find the exact cause. (Actually, I'm not familiar with the nimble streamer :)
I'll let you know the results as soon as possible.

**Comment by davidghukasyan** [comment] 2019-02-11 14:17
thanks a lot, will be waiting for a feedback.

**Comment by sfreet** [comment] 2019-02-12 10:52
This issue was resolved in version f1e60e31d1c3d04543b22a8cee25fb24b9cee913.
(It turns out that this problem has nothing to do with nimble streamer)
If the problem persists, please let me know again.
Thank you again for your contributions David.

**Comment by davidghukasyan** [comment] 2019-02-12 11:26
now I get an info during the installation.

[  2/166|  1%] [static] libovcrypto.a: C++ projects/base/ovcrypto/certificate.cpp => intermediates/DEBUG/objs/base/ovcrypto/certificate.o
projects/base/ovcrypto/certificate.cpp: In constructor ‘Certificate::Certificate(X509*)’:
projects/base/ovcrypto/certificate.cpp:10:2: error: ‘X509_up_ref’ was not declared in this scope
  X509_up_ref(_X509);
  ^~~~~~~~~~~

**Comment by sfreet** [comment] 2019-02-12 11:54
Is it the same system you used the last time?

**Comment by davidghukasyan** [comment] 2019-02-12 13:20
Yes its the same system.
Unfortunatly it doesnt help.
I even tried to download instead of git, but the result is same.

[ 10/175|  5%] [static] libovcrypto.a: C++ projects/base/ovcrypto/base_64.cpp => intermediates/DEBUG/objs/base/ovcrypto/base_64.o
[ 11/175|  6%] [static] libovcrypto.a: C++ projects/base/ovcrypto/certificate.cpp => intermediates/DEBUG/objs/base/ovcrypto/certificate.o
projects/base/ovcrypto/certificate.cpp: In constructor ‘Certificate::Certificate(X509*)’:
projects/base/ovcrypto/certificate.cpp:10:2: error: ‘X509_up_ref’ was not declared in this scope
  X509_up_ref(_X509);
  ^~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
core/build_objects.mk:18: recipe for target 'intermediates/DEBUG/objs/base/ovcrypto/certificate.o' failed
make: *** [intermediates/DEBUG/objs/base/ovcrypto/certificate.o] Error 1

**Comment by sfreet** [comment] 2019-02-13 02:37
Good morning David.
"'X509_up_ref' was not declared in this scope" means that the SSL header is not found or is an older header.
I think your system's ssl library version has changed since the last installation. (Of course, It's not your intentional action - when you install other programs)
First, check out the openssl version as follows
```
$ openssl version
OpenSSL 1.1.0g 2 Nov 2017
```
Next, checking the header location
```
$ pkg-config --cflags openssl
-I /usr/local/ include
```
Next, checking the function
```
$ cat /usr/local/include/openssl/x509.h | grep X509_up_ref
int X509_up_ref (X509 * x);

```
It is normal that X509_up_ref should be searched.
If not, try reinstalling ssl library for your OS as described in OvenMediaEngine.
(ex. ubuntu - apt install libssl-dev, fedora - yum install openssl-devel, centos - OpenSSL 1.1.0g Download and make install)

If this does not solve the above problem, please let me know your system information(OS name, version) with the above command execution result. 
Thnak you~

**Comment by davidghukasyan** [comment] 2019-02-13 11:06
hi , thank you , Openssl reinstall helped.
I am getting  
I 3565 TranscodeStream | transcode_stream.cpp:437  | Queue(filtered) is full, please decrease encoding options(resolution,bitrate,framerate)
I configured 1280x720 , 1800000 bitrate, which is a minimum requirment for me, is there any way to increase the queue/frame buffer ?

**Comment by sfreet** [comment] 2019-02-14 04:59
Do you have any problems with playing the media?
The message is not an error message and can be safely ignored if it is not repeated frequently and continuously.
(Increasing buffer isn't  a solution)
If there is a problem with media playback and the message continues to repeat, try lowering the resolution, bitrate.
If it is not possible to do so, one solution is to use a higher specification system than the one you are using now.

**Comment by sfreet** [comment] 2019-02-27 04:46
I close this issue. If the issue is not resolved, please let us know again.
Thanks again for your contributions @davidghukasyan

**Closed by sfreet** 2019-02-27 04:46 UTC
