### ISSUE TITLE
Very slow video / Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold

### ISSUE THREAD

**Issue by sephentos** [AirenSoft/OvenMediaEngine#295] opened 2021-02-24 14:12 UTC
Streaming with WebRTC is very slow in the video while audio is perfect.
In the logs there are multiple threshold warnings to notice.
They almost directly come after starting to stream and went fromt 120 in ther queue to 1163 just within one minute.

```
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 120, threshold: 120, peak: 120
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 198, threshold: 120, peak: 198
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 274, threshold: 120, peak: 275
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 349, threshold: 120, peak: 350
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 425, threshold: 120, peak: 426
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 501, threshold: 120, peak: 501
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 574, threshold: 120, peak: 574
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 649, threshold: 120, peak: 649
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 720, threshold: 120, peak: 721
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 798, threshold: 120, peak: 798
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 869, threshold: 120, peak: 870
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 945, threshold: 120, peak: 946
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 1019, threshold: 120, peak: 1022
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 1090, threshold: 120, peak: 1094
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 1168, threshold: 120, peak: 1173
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 1239, threshold: 120, peak: 1242
W [Decoderh264:718] ov.Queue | queue.h:192  | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 1316, threshold: 120, peak: 1319
```

Since you can see vp8 mentioned which is needed for WebRTC, if I understood correctly (correct me when I'm wrong), the video slows down - or is there any other issue?

**OBS Settings**
![grafik](https://user-images.githubusercontent.com/35430448/109011400-1e9fa500-76b1-11eb-9987-5e3436dac881.png)

**OME Log**
[https://pastebin.com/25B6NgXV](https://pastebin.com/25B6NgXV)

**Server.xml**
[https://pastebin.com/JLGWNPvR](https://pastebin.com/JLGWNPvR)

**System**
Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (4 cores)
8GB RAM
Ubuntu 18.0.4.5
OME: [latest master](https://github.com/AirenSoft/OvenMediaEngine/commit/3d642e9c42863ca053dab3dbd65b7b706355b0fc), which should be at least v0.11.0
Tested in Chrome and Firefox (both latest)

**Additional info**

- I am using the latest master branch (currently [3d642e9](https://github.com/AirenSoft/OvenMediaEngine/commit/3d642e9c42863ca053dab3dbd65b7b706355b0fc)) 
- We desire to only use WebRTC and to stream to 20-30 viewers; If possible in Full HD quality. 
Too less hardware power? Wrong Server.xml settings? What do you think?

Any help would be greatly appreciated.

**Comment by sephentos** [comment] 2021-02-24 14:44
Update:

I've asked a friend to test the stream too and he tells me about this issue:

```
WebRTC: ICE failed, add a STUN server and see about:webrtc for more details
```

Meanwhile when he connects he generates these messages in the OME log:

```
Signalling | rtc_signalling_server.cpp:756  | [Host -> OME] The host peer sents an empty candidate
W [PhyPortDgSock:3012] Ice | ice_port.cpp:868  | Could not find ice port information
W [PhyPortDgSock:3013] Ice | ice_port.cpp:868  | Could not find ice port information
W [PhyPortDgSock:3014] Ice | ice_port.cpp:868  | Could not find ice port information
W [PhyPortDgSock:3015] Ice | ice_port.cpp:868  | Could not find ice port information
W [PhyPortDgSock:3016] Ice | ice_port.cpp:868  | Could not find ice port information
```

Tried with tcprelay and without. All with WSS.

**Comment by getroot** [comment] 2021-02-25 02:02
> W [Decoderh264:718] ov.Queue | queue.h:192 | [0x7fbf682a0288] Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold: queue: 120, threshold: 120, peak: 120

The meaning of this log is that your server is not fast enough to do the encoding you set. In my experience, it may be difficult to perform encoding for two 1080p outputs with 4 core. Try setting it like this:

```
<OutputProfile>
	<Name>bypass_stream</Name>
	<OutputStreamName>${OriginStreamName}</OutputStreamName>
	<Encodes>
		<Video>
			<Bypass>true</Bypass>
		</Video>
		<Audio>
			<Codec>opus</Codec>
			<Bitrate>128000</Bitrate>
			<Samplerate>48000</Samplerate>
			<Channel>2</Channel>
		</Audio>
	</Encodes>
</OutputProfile>
```

**Comment by getroot** [comment] 2021-02-25 02:14
> WebRTC: ICE failed, add a STUN server and see about:webrtc for more details

This means that the STUN packet sent by the player was not received by the server. It can have several causes. I don't know exactly your environment, so I have to check all the possibilities. This is difficult.

(1) firewall

(2) Network configuration or packet loss

Settings should be changed depending on whether a public IP is assigned to the local interface or whether a packet to an external public IP such as AWS is forwarded.

Most of the packet loss issues are solved by connecting via TCP, but the following settings may be required depending on your server's network configuration. Is your server an instance of the cloud?

https://airensoft.gitbook.io/ovenmediaengine/v/master/streaming/webrtc-publishing#webrtc-over-tcp

Set `<StunServer>` or set your public IP in `<TcpRealy>` and `<IceCandidate>`.

And have you tried playing with wss://host:port/app/stream?transport=tcp?

(3) Due to insufficient server performance, STUN packets cannot be processed quickly enough to respond (possibly related to the above issue)

(4) SELinux

**Comment by sephentos** [comment] 2021-02-25 18:52
@getroot 

Answering to both answers...

`StunServer` has been set to a google stun server, now it works better.

I've changed the cpu cores to 8 and now the treshold notices went away, but instead of them there are new threshold warnings but now with WebRTC mentioned (before it was VP8).

```
[Host -> OME] The host peer sents an empty candidate
WebRTC Publisher Application/#default#app/stream StreamWorker Queue size has exceeded the threshold: queue: 55595, threshold: 500, peak: 55595
WebRTC Publisher Application/#default#app/stream StreamWorker Queue size has exceeded the threshold: queue: 79015, threshold: 500, peak: 79015
WebRTC Publisher Application/#default#app/stream StreamWorker Queue size has exceeded the threshold: queue: 93916, threshold: 500, peak: 93916```

Thats a huge increase just within one minute. Fetching the stream was not possible anymore.

```And have you tried playing with wss://host:port/app/stream?transport=tcp?```

Only using ?transport=tcp because it works much better.

```
(1) firewall
(4) SELinux
```

both can't be problematic. While testing firewalls are disabled.


```
If server performance is insufficient, and if you can control the input quality, do not server encoding and pass-through the stream from OBS. Try setting it like this:

		<Video>
			<Bypass>true</Bypass>
		</Video>
```

I've read in multiple threads not to do this because VP8 is needed for WebRTC. I can't choose VP8 within OBS, so don't I have to use VP8 in Server.xml?
Anyway, the `Input queue of transcode encoder. codec(vp8/139) size has exceeded the threshold:` have gone since I've upgraded to 8 cores. Somehow WebRTC now just makes problems.

**Comment by getroot** [comment] 2021-02-26 04:02
[1] StreamWorker is a thread that packages and transmits. If the transmission is slow, the queue may overflow. It means that the transfer rate between server and player is lower than the output bitrates. In the case of UDP, if it cannot be transmitted, it ends as it is, but in the case of TCP, this happens because retransmission is attempted continuously. Combining the information you have provided from the past, the network between your server and player appears to be very slow or unstable. Measure the network speed between your server and player with a tool like iperf.

[2] Currently, most browsers support H264 in WebRTC. (In the early days of WebRTC, only VP8 was supported, but now it is not.) Chrome, firefox, and safari all support H.264, so you can service only with H.264 unless there is a special case. If you know a browser that doesn't support WebRTC H.264, please let me know explicitly.

[3] Let us clarify your problem. Now you are having two problems. And each problem can be affecting each other.
1. Issue of lack of transcoding performance
2. Network issues (packet loss or very slow)

First of all, it would be better to remove the first problem and then solve the second problem. To do this, bypass transcoding and test. And let me know the result.

Your issue is not reproduced for most people, including me. In some environments, a single server provides streaming to more than 1000 people. It's also a good idea to check what makes your environment different. (CPU utilization, memory utilization, network speed between flare and server, Linux kernel network buffer tuning, etc.)

**Comment by getroot** [comment] 2021-04-23 07:37
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.

**Closed by getroot** 2021-04-23 07:37 UTC
