### ISSUE TITLE
WebRTC input "cannot find stream"

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#364] opened 2021-05-07 20:58 UTC
**Describe the bug**
When streaming to OME via WebRTC input with no errors, WebRTC will not play.

**To Reproduce**
1. [Server.xml](https://gist.github.com/naanlizard/5d50fd7e37ad26efcd54b4ab2c34e23e)
2. Run above Server.xml in docker 0.11.3
3. Send input stream via WebRTC input demo page [here ](https://demo.ovenplayer.com/demo_input.html) destination is wss://domain:3334/live/stream?direction=send&transport=tcp
4. Attempt playback via demo playback page
5. observe no playback (connection with webrtc server failed)

**Expected behavior**

**Logs**
[Log file](https://gist.github.com/naanlizard/b45bdb085d2271b422a23864d0134e65)

Not shown in that log, but occasionally I get "invalid VP8 bitstream" too, not sure what's up with that

**Server (please complete the following information):**
 - OS: Ubuntu 20.04 Server
 - OvenMediaEngine Version: 0.11.3 (docker)
 - Branch: release

**Player (please complete the following information):**
 - Device: PC
 - OS: Windows 10 LTSC
 - Browser Chrome Version 90.0.4430.93 (Official Build) (64-bit)

**Additional context**
https://i.imgur.com/zCHTWcx.png

https://i.imgur.com/XqYknf7.png

I imagine I am simply misconfigured somewhere, but I'm not sure where after going through the docs a few times.

**Comment by getroot** [comment] 2021-05-10 01:59
Have you ever used Display Capture as a video source on the demo.ovenplayer.com page? Display capture currently has a known issue that does not work well at high resolutions and bitrates. You need to analyze it accurately, but the browser is transmitting the key frame at a very late period (about 120 seconds or more).
We are looking to see if we can fix this.

Can you check if the problem is reproduced by selecting OBS's virtual cam or physical cam as the video source?

And since 0.11.3, many problems have been solved, so please check with master as well.

**Comment by naanlizard** [comment] 2021-05-10 02:02
I will try master branch soon.

With my testing, I used an (approximately) 1200x800 window capture in the browser, NOT a display capture.

**Comment by getroot** [comment] 2021-05-10 02:04
![image](https://user-images.githubusercontent.com/17779085/117596888-5b8f1a00-b17f-11eb-8aa4-0811073124b6.png)

Yes, what I meant was the selection of "Display capture" on demo.ovenplayer.com. That works weird right now. I looked at your capture screen again and checked it.

**Comment by getroot** [comment] 2021-05-10 02:10
Yes, we are also eagerly looking to see if this is a problem we can solve. (Exactly, this is an issue on the OvenPlayer side.)

Why is the browser not sending or sending the key frame late even though OME is sending FIR very often when OvenPlayer tries Display Capture? I am looking for a cause for this.

**Comment by getroot** [comment] 2021-06-08 11:31
We are doing some work and testing for Display Capture. If there is an update, I will register it as a new issue. I close this issue.

**Closed by getroot** 2021-06-08 11:31 UTC
