### ISSUE TITLE
SIGSEGV in docker

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#208] opened 2020-10-27 16:07 UTC
**Describe the bug**
While running in docker, occasionally OME crashes due to SIGSEGV. This has happened twice in two days.

**To Reproduce**
[Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5446499/Server.xml.txt)
[Dockerfile.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5446492/Dockerfile.txt)
[docker-compose.yml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5446493/docker-compose.yml.txt) 

We run the docker server with the above settings and forward rtmp streams from our nginx-rtmp server to OME via ffmpeg
like ffmpeg -i rtmp://hostname.tld:1935/live/{stream.id} -acodec copy -vcodec copy -f flv rtmp://localhost:1951/lowlatency/#{stream.id}

Typically we have anywhere from 1 to 30 streams, it has been crashing in lower-usage periods.

**Expected behavior**
No Segfault crash

**Logs**
[omelog.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5446468/omelog.txt)

**Server (please complete the following information):**
 - OS: Ubuntu 18.04.2
 - OvenMediaEngine Version: 0.10.7
 - Branch: unsure

**Player (please complete the following information):**
N/A

**Additional context**
This is running on a relatively lightly loaded server, with plenty of RAM. 

Apologies that the SIGSEGV isn't actually in the log file I uploaded, I swear it was in the docker logs output at the end, but apparently it wasn't copied when I did `docker logs container > omelog.txt`

**Comment by getroot** [comment] 2020-10-28 07:14
Sorry, ovenmediaengine:latest wasn't the latest version, I just updated ovenmediaengine:latest to the latest release (0.10.8).
Could you test it again? As you can see, you have to give "docker build. --No-cache=true" option when building docker.

**Comment by naanlizard** [comment] 2020-10-28 16:33
Done, I'll open a new issue if it crashes again, as I see 10.8 has some updates to fix segfaults.

Thank you as always for your hard work :)

**Comment by naanlizard** [comment] 2020-11-03 01:40
Reopening with a new log file - not sure if it's a sigsegv, but definitely something caused it to crash. Same setup as above but with 0.10.8 of course.

[omelog.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5478859/omelog.txt)

**Comment by getroot** [comment] 2020-11-03 07:36
I can't reproduce this.
Can you recreate the image after removing the strip from the Dockerfile, and deliver the crash log created after the crash occurred? (It will be in the same path as the executable file. /opt/ovenmediaengine/bin)

```
RUN \
        DIR=/tmp/ome && \
        cd ${DIR} && \
        cd src && \
        mkdir -p ${PREFIX}/bin/origin_conf && \
        mkdir -p ${PREFIX}/bin/edge_conf && \
        # strip ./bin/RELEASE/OvenMediaEngine && \ <-- remove this line
        cp ./bin/RELEASE/OvenMediaEngine ${PREFIX}/bin/ && \
        cp ../misc/conf_examples/Origin.xml ${PREFIX}/bin/origin_conf/Server.xml && \
        cp ../misc/conf_examples/Logger.xml ${PREFIX}/bin/origin_conf/Logger.xml && \
        cp ../misc/conf_examples/Edge.xml ${PREFIX}/bin/edge_conf/Server.xml && \
        cp ../misc/conf_examples/Logger.xml ${PREFIX}/bin/edge_conf/Logger.xml && \
        rm -rf ${DIR}
```

Thanks for your contribution.

**Comment by naanlizard** [comment] 2020-11-03 18:28
I have not changed anything yet (haven't had a good chance to take it down) but I did just have another crash.

Excerpt from docker logs - 

```
[Stream Info]
id(54), name(56723), SourceType(Rtmp), Created Time (Thu Jan  1 00:00:00 1970)

        Video Track #0: Bypass(false) Bitrate(2.50Mb) codec(1, H264) resolution(1920x1080) framerate(60.00fps) timebase(1/1000)
        Audio Track #1: Bypass(false) Bitrate(160.00Kb) codec(6, AAC) samplerate(44.1K) format(s16, 16) channel(mono, 1) timebase(1/1000)
[2020-11-03 18:23:15.777] I 88 MediaRouter.Stream | mediarouter_stream.cpp:59   | Trying to create media route stream: name(56723) id(54)
[2020-11-03 18:23:15.777] I 88 Monitor | application_metrics.cpp:56   | Create StreamMetrics(56723) for monitoring
[2020-11-03 18:23:15.778] I 88 TranscodeStream | transcode_stream.cpp:491  | [#default#lowlatency/56723(54)] -> [#default#lowlatency/56723(2926985924)] Output stream has been created.
[2020-11-03 18:23:15.778] I 88 MediaRouter.App | mediarouter_application.cpp:182  | Trying to create a stream: [#default#lowlatency/56723(2926985924)]
[2020-11-03 18:23:15.778] I 88 MediaRouter.App | mediarouter_application.cpp:183  |
[Stream Info]
id(2926985924), name(56723), SourceType(Transcoder), Created Time (Tue Nov  3 18:23:15 2020)
        >> Origin Stream Info
        id(54), name(56723), SourceType(Rtmp), Created Time (Thu Jan  1 00:00:00 1970)

        Video Track #0: Bypass(true) Bitrate(2.50Mb) codec(1, H264) resolution(1920x1080) framerate(60.00fps) timebase(1/90000)
        Audio Track #1: Bypass(true) Bitrate(160.00Kb) codec(6, AAC) samplerate(48.0K) format(s16, 16) channel(mono, 1) timebase(1/48000)
        Audio Track #2: Bypass(false) Bitrate(128.00Kb) codec(8, OPUS) samplerate(48.0K) format(s16, 16) channel(stereo, 2) timebase(1/48000)
[2020-11-03 18:23:15.778] I 88 MediaRouter.Stream | mediarouter_stream.cpp:59   | Trying to create media route stream: name(56723) id(2926985924)
[2020-11-03 18:23:15.778] I 88 Monitor | application_metrics.cpp:56   | Create StreamMetrics(56723) for monitoring
[2020-11-03 18:23:15.778] I 88 WebRTC | rtc_stream.cpp:259  | Unsupported codec(Audio/AAC) is being input from media track
[2020-11-03 18:23:15.779] I 88 Publisher | stream.cpp:180  | WebRTC Publisher Application application has started [56723(2926985924)] stream
[2020-11-03 18:23:15.779] I 88 Publisher | stream.cpp:180  | OVTPublisher Application application has started [56723(2926985924)] stream
[2020-11-03 18:23:15.779] I 88 Publisher | stream.cpp:180  | RtmpPushPublisher Application application has started [56723(2926985924)] stream
[2020-11-03 18:23:15.779] I 88 TranscodeStream | transcode_stream.cpp:127  | [#default#lowlatency/56723(54)] Transcoder input stream has been started. Status : (1) Decoders, (1) Encoders
[2020-11-03 18:23:15.780] I 103 TranscodeCodec | transcode_codec_dec_aac.cpp:49   | [#default#lowlatency/56723(54)] input stream information: [audio] aac (LC), 44100 Hz, stereo, fltp, 4 kbps, timebase: 1/1000, frame_size: 1024
[2020-11-03 18:23:20.501] I 98 RtmpProvider | rtmp_provider.cpp:118  | The RTMP client has disconnected: [#default#lowlatency/56723], remote: <ClientSocket: 0x7f8b98014570, #54, state: 4, TCP, 127.0.0.1:57298>
[2020-11-03 18:23:20.501] I 98 Provider | stream.cpp:55   | #default#lowlatency/56723(54) has been stopped playing stream
[2020-11-03 18:23:20.501] I 98 MediaRouter.App | mediarouter_application.cpp:345  | Trying to delete a stream: [#default#lowlatency/56723(54)]
[2020-11-03 18:23:20.501] C 88 OvenMediaEngine | signals.cpp:119  | OME received signal 11 (SIGSEGV), interrupt.
[2020-11-03 18:23:20.501] I 98 Monitor | application_metrics.cpp:68   | Delete StreamMetrics(56723) for monitoring
[2020-11-03 18:23:20.501] I 98 Monitor | stream_metrics.cpp:31   |
[Stream Info]
id(54), name(56723), SourceType(Rtmp), Created Time (Thu Jan  1 00:00:00 1970)

        Video Track #0: Bypass(false) Bitrate(2.50Mb) codec(1, H264) resolution(1920x1080) framerate(60.00fps) timebase(1/1000)
        Audio Track #1: Bypass(false) Bitrate(160.00Kb) codec(6, AAC) samplerate(44.1K) format(fltp, 32) channel(stereo, 2) timebase(1/1000)

        >> Statistics
        Last update time : Tue Nov  3 18:23:20 2020, Last sent time : Tue Nov  3 18:23:15 2020
        Bytes in : 218.36KB, Bytes out : 0B, Concurrent connections : 0, Max connections : 0 (Tue Nov  3 18:23:15 2020)

                >>>> By publisher
                - Unknown : Bytes out(0B) Concurrent Connections (0)
                - WebRTC : Bytes out(0B) Concurrent Connections (0)
                - RTMP : Bytes out(0B) Concurrent Connections (0)
                - RTMPPush : Bytes out(0B) Concurrent Connections (0)
                - HLS : Bytes out(0B) Concurrent Connections (0)
                - DASH : Bytes out(0B) Concurrent Connections (0)
                - LLDASH : Bytes out(0B) Concurrent Connections (0)
                - Ovt : Bytes out(0B) Concurrent Connections (0)
                - File : Bytes out(0B) Concurrent Connections (0)

[2020-11-03 18:23:20.501] I 98 TranscodeStream | transcode_stream.cpp:1127 | [#default#lowlatency/56723(54)] -> [#default#lowlatency/56723(2926985924)] Transcoder output stream has been deleted.
[2020-11-03 18:23:20.501] I 98 MediaRouter.App | mediarouter_application.cpp:345  | Trying to delete a stream: [#default#lowlatency/56723(2926985924)]
[2020-11-03 18:23:20.501] I 98 Monitor | application_metrics.cpp:68   | Delete StreamMetrics(56723) for monitoring
[2020-11-03 18:23:20.502] I 98 Monitor | stream_metrics.cpp:31   |
[Stream Info]
id(2926985924), name(56723), SourceType(Transcoder), Created Time (Tue Nov  3 18:23:15 2020)
        >> Origin Stream Info
        id(54), name(56723), SourceType(Rtmp), Created Time (Thu Jan  1 00:00:00 1970)

        Video Track #0: Bypass(true) Bitrate(2.50Mb) codec(1, H264) resolution(1920x1080) framerate(60.00fps) timebase(1/90000)
        Audio Track #1: Bypass(true) Bitrate(160.00Kb) codec(6, AAC) samplerate(44.1K) format(s16, 16) channel(stereo, 2) timebase(1/48000)
        Audio Track #2: Bypass(false) Bitrate(128.00Kb) codec(8, OPUS) samplerate(48.0K) format(s16, 16) channel(stereo, 2) timebase(1/48000)

        >> Statistics
        Last update time : Tue Nov  3 18:23:15 2020, Last sent time : Tue Nov  3 18:23:15 2020
        Bytes in : 0B, Bytes out : 0B, Concurrent connections : 0, Max connections : 0 (Tue Nov  3 18:23:15 2020)

                >>>> By publisher
                - Unknown : Bytes out(0B) Concurrent Connections (0)
                - WebRTC : Bytes out(0B) Concurrent Connections (0)
                - RTMP : Bytes out(0B) Concurrent Connections (0)
                - RTMPPush : Bytes out(0B) Concurrent Connections (0)
                - HLS : Bytes out(0B) Concurrent Connections (0)
                - DASH : Bytes out(0B) Concurrent Connections (0)
                - LLDASH : Bytes out(0B) Concurrent Connections (0)
                - Ovt : Bytes out(0B) Concurrent Connections (0)
                - File : Bytes out(0B) Concurrent Connections (0)

[2020-11-03 18:23:20.502] I 98 Publisher | stream.cpp:244  | [56723(2926985924)] WebRTC Publisher Application stream has been stopped
[2020-11-03 18:23:20.505] I 98 Publisher | stream.cpp:244  | [56723(2926985924)] OVTPublisher Application stream has been stopped
[2020-11-03 18:23:20.505] I 98 Publisher | stream.cpp:244  | [56723(2926985924)] RtmpPushPublisher Application stream has been stopped
[2020-11-03 18:23:20.505] I 98 MediaRouter.Stream | mediarouter_stream.cpp:79   | Delete media route stream name(56723) id(2926985924)
[2020-11-03 18:23:20.505] I 98 TranscodeStream | transcode_stream.cpp:171  | [#default#lowlatency/56723(54)] Transcoder input stream has been stopped.
```

**Comment by getroot** [comment] 2020-11-04 06:18
Sorry, but I can't analyze this with OME logs. I need a CRASH DUMP file. A "CRASH DUMP" file should have been created inside Docker. Could you please upload it? Crash dump file is created like "crash_20201102.dump".

However, in the Docker image, the symbol is stripped. So, as I mentioned above, if a crash occurs after removing the strip and recreating the docker image and using it, uploading a crash dump will help a lot in solving the problem.

**Comment by naanlizard** [comment] 2020-11-04 17:22
Yes, I am aware, I've rerun the docker container with the new dockerfile, which should create a crash file if it crashes again.

I posted the log in case it was helpful.

**Comment by getroot** [comment] 2020-11-09 09:46
I am very interested in this issue and I am waiting for any updates of your crash dump file.

**Comment by getroot** [comment] 2020-11-09 14:34
I was able to reproduce the crash bug by using a script that looped through stream creation and deletion infinitely. And I solved that problem. I hope this solves your problem too. (If this isn't the one that bothers you, of course I'll go hunting for bugs again.)

Could you help me with testing using **airensoft/ovenmediaengine:dev** or **master branch**? I hope there are no more crashes for you!

The latest source has made a lot of changes to the configuration file. To use the latest master source with your existing Server.xml, please refer to the manual https://airensoft.gitbook.io/ovenmediaengine/v/0.10.9/. It doesn't matter if you use Docker.

**Comment by naanlizard** [comment] 2020-11-09 19:58
I'll get my instance up and running ASAP, it will take a little time to adjust my config and find a good downtime.

Will the fix you wrote be in 0.10.9? It may be easier if it is

**Comment by getroot** [comment] 2020-11-10 04:48
I haven't released 0.10.9 because we haven't finished testing yet. The latest patch can only be used with the master branch or airensoft/ovenmediaengine:dev.

**Comment by naanlizard** [comment] 2020-11-10 16:12
Just started an instance with the master branch.

It appears that the new config needs both Stream.Name and Stream.OutputStreamName - the documentation you link above does not list OutputStreamName. Possibly this is a bug?

**Comment by naanlizard** [comment] 2020-11-10 18:45
A few things

1. Even rebuilt (with this dockerfile) the server reports version 0.10.8 in the logs - expected? Should be building from master branch [Dockerfile.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5519512/Dockerfile.txt)

2. Had another SIGSEGV but no crash dump created as I forgot to edit the Dockerfile first. I had supposedly rebuilt the server but it was cached from a previous creation, so I'm not sure it included the new fix

3. I just rebuilt the docker image with --no-cache and it seemed to actually build it. Running now and if it crashes again I'll drop a crash log here.

**Comment by naanlizard** [comment] 2020-11-11 00:33
No crashes so far, but after some hours I got a ton of messages like the following in queue, and could not connect any more viewers to the WebRTC player.

`[2020-11-11 00:29:46.195] W 42 ov.Queue | queue.h:179  | [0x7fbc7c00c578] ClientSocket #34 IPRemoved:52425 (of #6) size has exceeded the threshold: queue: 200, threshold: 100`

This didn't happen on the previous versions that I can recall. This is using the master branch as of ~6 hours ago (previous comment)

Restarting OME fixes it, I will report if it breaks again. It's not a crash, and there is nothing else useful in the logs that I can see

**Comment by getroot** [comment] 2020-11-11 03:59
> Just started an instance with the master branch.
> 
> It appears that the new config needs both Stream.Name and Stream.OutputStreamName - the documentation you link above does not list OutputStreamName. Possibly this is a bug?

The manual has not been updated yet.

>[2020-11-11 00:29:46.195] W 42 ov.Queue | queue.h:179 | [0x7fbc7c00c578] ClientSocket #34 IPRemoved:52425 (of #6) size has exceeded the threshold: queue: 200, threshold: 100

This can happen when socket send is slow, but I've never seen it. I will analyze this too.

Thank you for your continued contribution.

**Comment by bhanuc** [comment] 2020-11-11 14:55
Facing the same issue as naanlizard, using the latest git version - getting queue: 824, threshold: 100 in the logs. I am also getting WebSocket opening handshake timed out when trying to connect to the websocket server. Restarting the server fixes the issue.

**Comment by naanlizard** [comment] 2020-11-11 15:16
The way to reproduce the issue bhanuc and I have is to leave the server running for 12+hours. It happened again for me this morning. Should we open a new ticket?

**Comment by getroot** [comment] 2020-11-12 08:02
@bhanuc @naanlizard 
I found and fixed WebRTC's deadlock possibility in my recently modified code. Thank you for reporting the problem. I hope this has completely solved your problem.

**Comment by naanlizard** [comment] 2020-11-12 15:26
I will try the master branch today. Thanks!

**Comment by naanlizard** [comment] 2020-11-14 01:36
No problems after about a day, where before I'd have expected it to stop serving requests or crash. I think we can close this ticket. Thanks for the quick fix!

**Comment by getroot** [comment] 2020-11-16 02:09
That’s very good news,
Thank you for contributing to open source.

**Closed by getroot** 2020-11-16 02:09 UTC
