### ISSUE TITLE
CrossDomains feature broken for HLS

### ISSUE THREAD

**Issue by basisbit** [AirenSoft/OvenMediaEngine#621] opened 2022-01-03 15:12 UTC
**Describe the bug**
The CORS / CrossDomains feature with wildcard subdomains does not work any more in current versions of OME. It seems like the CrossDomains tag within Application->Publisher->HLS is just ignored or not applied any more.

**To Reproduce**
1. Set up OME edge with Application->Publisher->HLS->CrossDomains with some `*.yourdomain.com` entry. Have the server be accessible at something like `somesubdomain1.yourdomain.tld`
2. Set up OvenPlayer or any other hls.js based player on a website on another server at something like `somesubdomain2.yourdomain.com`
3. Try to make OvenPlayer play a HLS stream from your OME edge server

**Expected behavior**
Video should play just fine and HTTP response headers should be filled correctly so that no CORS error happens.

**Logs**
Nothing unusual, but log level is set to only log errors, for data privacy and performance reasons.

**Server (please complete the following information):**
 - OS: Ubuntu Server 20.04 HWE
 - OvenMediaEngine Version: current pulled at 2022-01-01
 - Branch: master

**Player (please complete the following information):**
 - Browser: Chromium
 - Version: 99.0/current

**Additional context**
Worked fine in master form ~ half a year ago.
Streams play fine over UDP & TCP based WebRTC.
The provided certificate for OME is a wildcard certificate which fits for this domain.
HLS playback in VLC works fine.

**Comment by dimiden** [comment] 2022-01-04 03:43
@basisbit 
Thank you for the detailed bug reporting.
I checked that there was a problem when wildcard was used for CORS-related code that was recently modified.
I'll notify you when it's fixed.

**Comment by dimiden** [comment] 2022-01-04 07:54
@basisbit 
I thought this issue was important and solved it by raising the priority as much as possible.

**Comment by basisbit** [comment] 2022-01-05 02:28
@dimiden HLS playback still seems to be broken. Edge server returns HTTP 404 for playlist.m3u8 requests.
Log looks like this:
> edge_1  | [2022-01-05 02:23:15.246] E [SegWorker:24] HLS | hls_stream_server.cpp:60   | [#default#app/stream123] [HLS] Could not find: playlist.m3u8 (404)

**Comment by dimiden** [comment] 2022-01-05 04:30
@basisbit 
I tried playing HLS in my edge, but I didn't find any problems.
Since the CORS error is an error that occurs on the client-side, I think the server's 404 error is caused by another cause.
To solve this problem quickly, could you test ```<CrossDomain>``` with ```*```? I think it will be a different cause if it doesn't play even though it's changed.

**Comment by basisbit** [comment] 2022-01-05 23:19
It works when using `<CrossDomains><Url>*</Url></CrossDomains>` but not with `*.somedomain.com`. Good enough for me this weekend^^ Thank you!

**Comment by dimiden** [comment] 2022-01-06 02:43
@basisbit 
That's a very strange situation.
Even if the OME doesn't have CORS settings, the OME must receive stream from the origin because it has received HTTP requests. (CORS settings only affect client-side)
Since the log you sent me has '404 not found' error, I expected that there would be an incorrect stream or origin setting, but I think there is another problem that I cannot predict because it worked well after changing the ```<CrossDomains>``` setting to ```*```.

If you need more support for this issue, could you upload your ENTIRE ```Server.xml``` of origin and edge? Sensitive data can be changed to any string such as certificate/domain, etc.

**Comment by basisbit** [comment] 2022-01-06 07:59
as usual, the full config I use can be found here: https://github.com/basisbit/OvenMediaEngine/tree/master/local-data

**Comment by basisbit** [comment] 2022-01-13 02:37
Can this please be reopened, because it is not fixed? I consider using `*` to only be a workaround.

**Comment by dimiden** [comment] 2022-01-13 03:14
@basisbit 
I forgot that I was dealing with this issue. I reopened this issue, and I will analyze it.

**Comment by dimiden** [comment] 2022-01-24 08:38
@basisbit 
I configured and tested based on your setting, but I didn't find any issues related to CORS.
The settings that I tested are as follows:
- OME Version: ae14b73ca2c51d69694a16a8ea9339d5857e8ab5
- Settings  (Note - Settings that are not related to CORS are joined in a single line, so they may look weird. :))
  - [Origin]
   ```
   <?xml version="1.0" encoding="UTF-8"?>
   
   <Server version="8">
   	<Name>OvenMediaEngine</Name>
   	<Type>origin</Type><IP>*</IP>
   	<Bind>
   		<Providers><RTMP><Port>41935</Port></RTMP></Providers>
   		<Publishers><OVT><Port>49000</Port></OVT></Publishers>
   	</Bind>
   	<VirtualHosts><VirtualHost>
   		<Name>default</Name>
   		<Host>
   			<Names><Name>my-test.airensoft.com</Name></Names>
   			<TLS><CertPath>../../certs/_airensoft_com.crt</CertPath><KeyPath>../../certs/_airensoft_com.key</KeyPath><ChainCertPath>../../certs/_airensoft_com_chain.crt</ChainCertPath></TLS>
   		</Host>
   		<Applications><Application>
   			<Name>360out</Name>
   			<Type>live</Type>
   			<Providers><RTMP /></Providers>
   			<OutputProfiles><OutputProfile>
   				<Name>ingame</Name>
   				<OutputStreamName>${OriginStreamName}</OutputStreamName>
   				<Encodes>
   					<Audio><Bypass>true</Bypass></Audio>
   					<Video><Bypass>true</Bypass></Video>
   				</Encodes>
   			</OutputProfile></OutputProfiles>
   			<Publishers><OVT /></Publishers>
   		</Application></Applications>
   	</VirtualHost></VirtualHosts>
   </Server>
   ```
  - [Edge]
   ```
   <?xml version="1.0" encoding="UTF-8"?>
   <Server version="8">
   	<Name>OvenMediaEngine</Name>
   	<Type>edge</Type><IP>*</IP>
   	<Bind>
   		<Providers><OVT /></Providers>
   		<Publishers>
   			<HLS>
   				<Port>40080</Port>
   				<TLSPort>40443</TLSPort>
   			</HLS>
   		</Publishers>
   	</Bind>
   	<VirtualHosts><VirtualHost>
   		<Name>default</Name>
   		<Host>
   			<Names><Name>my-test.airensoft.com</Name></Names>
   			<TLS><CertPath>../../certs/_airensoft_com.crt</CertPath><KeyPath>../../certs/_airensoft_com.key</KeyPath><ChainCertPath>../../certs/_airensoft_com_chain.crt</ChainCertPath></TLS>
   		</Host>
   		<Origins>
   			<Properties>
   				<NoInputFailoverTimeout>3000</NoInputFailoverTimeout>
   				<UnusedStreamDeletionTimeout>15000</UnusedStreamDeletionTimeout>
   			</Properties>
   			<Origin>
   				<Location>/pony/</Location>
   				<Pass>
   					<Scheme>OVT</Scheme>
   					<Urls>
   						<Url>my-test.airensoft.com:49000/360out/</Url>
   					</Urls>
   				</Pass>
   			</Origin>
   		</Origins>
   		<Applications><Application>
   			<Name>pony</Name>
   			<Type>live</Type>
   			<Providers><OVT /></Providers>
   			<OutputProfiles><OutputProfile>
   				<Name>bypass_stream</Name>
   				<OutputStreamName>${OriginStreamName}</OutputStreamName>
   				<Encodes><Audio><Bypass>true</Bypass></Audio><Video><Bypass>true</Bypass></Video></Encodes>
   			</OutputProfile></OutputProfiles>
   			<Publishers>
   				<StreamWorkerCount>1</StreamWorkerCount><AppWorkerCount>1</AppWorkerCount>
   				<HLS>
   					<SegmentDuration>2</SegmentDuration>
   					<SegmentCount>3</SegmentCount>
   					<CrossDomains>
   						<Url>http?://*.ovenplayer.com</Url>
   					</CrossDomains>
   				</HLS>
   			</Publishers>
   		</Application></Applications>
   	</VirtualHost></VirtualHosts>
   </Server>
   ```
And, I published RTMP stream to the following RTMP URL using OBS,
- RTMP URL: rtmp://my-test.airensoft.com:49135/360out/stream/playlist.m3u8

and played the following HLS URL in https://demo.ovenplayer.com
- HLS URL: https://my-test.airensoft.com:40443/pony/stream/playlist.m3u8
   - [Link to demo.ovenplayer.com](https://demo.ovenplayer.com/#%7B%22playerOption%22%3A%7B%22autoStart%22%3Atrue%2C%22autoFallback%22%3Atrue%2C%22mute%22%3Afalse%2C%22sources%22%3A%5B%7B%22type%22%3A%22hls%22%2C%22file%22%3A%22https%3A%2F%2Fmy-test.airensoft.com%3A40443%2Fpony%2Fstream%2Fplaylist.m3u8%22%7D%5D%7D%2C%22demoOption%22%3A%7B%22autoReload%22%3Atrue%2C%22autoReloadInterval%22%3A2000%7D%7D)

and, everything worked well.


In addition, I found a part that needs one modification among settings that are not related to CORS.
While the ```<UnusedStreamDeletionTimeout>``` is ```15000```ms, the total length of the HLS segment is ```18000```ms (```<SegmentDuration> * <SegmentCount> = 6 * 3 = 18s = 18000ms```), so it cannot be played.
To solve this problem, it's recommended to reduce ```<SegmentDuration>``` or increase ```<UnusedStreamDeletionTimeout>```.

If there is any additional issue, please open this again.

**Comment by basisbit** [comment] 2022-01-24 13:12
@dimiden The issue was very easy to reproduce by setting CrossDomains for example like this:
```<Url>*.domain1.com</Url>
<Url>*.domain2.com</Url>
<Url>domain2.com</Url>```

I won't be able to test this again for the next couple of weeks because of there not being an event for the next couple of weeks, and I don't keep servers when they are not needed.

If specifying the protocol is mandatory, please edit your documentation.

Regarding your other recommendation, I'd love to reduce `SegmentDuration` but that breaks playback for many users because of OME still not supporting http1.1 and new tcp connections taking a looong time to ramp up to decent speed when the bandwidth x latency product is unfortunate. Regarding `UnusedStreamDeletionTimeout`, I had to reduce that to avoid issues of OBS disconnecting when the internet uplink of a streamer randomly dies and comes back with another IPv4 address. having the lower `UnusedStreamDeletionTimeout` was not a problem in my use case thanks to WebRTC viewers keeping the stream alive.

PS: closing issues like this just because you can't yet reproduce it, is rather rude. Meanwhile, you keep other solved issues open in the issue tracker for months without comments.

**Comment by dimiden** [comment] 2022-01-24 13:53
@basisbit 
Oh, I apologize if my behavior felt rude.

I've done enough testing and thought HLS was not "broken".
I thought it would be a setting problem with a very high probability, so I shared the working ```Server.xml``` and closed this issue.

As you said, the protocol should be specified in the ```<CrossDomain>``` setting, but I think I was confused because there was no mention of it.
I think specifying the protocol will probably solves this issue, and in order to prevent confusion among other users, I am thinking of developing it to support both http and https if the protocol is omitted.

Lastly, I'm doing my best to synchronize between code and issue using our issue tracker, but I'm too busy right now, so sometimes I miss update of issue. This is a problem that will be solved only when I'm less busy. :)
(FYI, Keep-alive task is also assigned as task for the first half of this year)

**Comment by dimiden** [comment] 2022-01-25 04:06
I reopened this task to close when it was confirmed that the problem was solved.

**Comment by Adam1901** [comment] 2022-02-01 14:18
Is it possible to update the edge configuration example file with cross domain. The XML configuration file I find can be a little ambigious at times

**Comment by dimiden** [comment] 2022-02-02 03:57
@Adam1901 
I just added some examples in ```conf_examples/Edge.xml``` and ```conf_examples/Server.xml```. Thanks! 19bc1a3fe87fbb6cc313ae954f3ac55fcc87da28

**Comment by Adam1901** [comment] 2022-02-02 11:24
> @Adam1901 I just added some examples in `conf_examples/Edge.xml` and `conf_examples/Server.xml`. Thanks! [19bc1a3](https://github.com/AirenSoft/OvenMediaEngine/commit/19bc1a3fe87fbb6cc313ae954f3ac55fcc87da28)

That has fixed the issue with HLS i've been seeing since 12.6

Thanks!

**Closed** 2022-02-21 18:40 UTC
Labels: bug
