### ISSUE TITLE
SRT Provider fails to bind IPv6 in 0.15.10

### ISSUE THREAD

**Issue by getroot** [AirenSoft/OvenMediaEngine#1241] opened 2023-05-18 03:05 UTC
I believe i found the issue on my configuration:
```xml
<Server>
  <IP>*</IP>
  <IP>::</IP>
</Server>
```

I have to test it, it everything works fine, now.
----
no idea why it works on:
- on v0.15.9 works with (without SRT and with http-websocket).
- on v0.15.10 it fails also on http-websocket setup (and enabled SRT).

so change after everythink the following (with SRT and http-websocket) on v0.15.10 everything start up like expected: 
```xml
<Server>
  <IP>*</IP>
</Server>
```

_Originally posted by @genofire in https://github.com/AirenSoft/OvenMediaEngine/discussions/1095#discussioncomment-5897560_

**Comment by getroot** [comment] 2023-05-18 03:08
@genofire I have created a new issue. If you attach the logs of 0.15.9 and 0.15.10 it will help to solve the problem.

**Comment by dimiden** [comment] 2023-05-18 17:00
To enable OME for both IPv4 and IPv6, socket creation, binding, and listening are performed for each respective socket family. To achieve this, the ```IPV6_V6ONLY``` option of the socket is used, and it works fine without any issues.

However, it seems that the ```SRTO_IPV6ONLY``` option, which is expected to perform the same function in SRT, is not functioning properly. Specifically, when this option is set and only an IPv4 address is used for listening, checking with ```netstat``` shows that it is bound only to the IPv4 address. Consequently, attempting to bind and listen on the same port with an IPv6 address results in an error, causing OME not to execute.

I have searched for possible solutions in the current version of SRT, which is 1.5.1, and previous versions, but I couldn't find an easy way to resolve this. Fortunately, it seems that this issue has been resolved in the latest version of [SRT 1.5.2-rc.2](https://github.com/Haivision/srt/tree/v1.5.2-rc.2). Therefore, I recommend updating the ```SRT_VERSION``` variable in ```prerequisites.sh``` from ```SRT_VERSION=1.5.1``` to ```SRT_VERSION=1.5.2-rc.2``` and executing ```prerequisites.sh``` again before compling OME.

**Comment by dimiden** [comment] 2023-08-17 05:43
This issue has been confirmed to be resolved in [SRT v1.5.2](https://github.com/Haivision/srt/releases/tag/v1.5.2).

**Closed by dimiden** 2023-08-17 05:43 UTC
Labels: resolved, external dependency

**Comment by genofire** [comment] 2023-08-17 10:06
does ovenmediaengine use this SRT lib already?

**Comment by dimiden** [comment] 2023-08-21 04:24
@genofire
Yes, OvenMediaEngine has been using SRT v1.5.2 since version [v0.15.14](https://github.com/AirenSoft/OvenMediaEngine/releases/tag/v0.15.14).
