### ISSUE TITLE
Docker image airensoft/ovenmediaengine:0.15.1 bootloops on Azure Container Instances

### ISSUE THREAD

**Issue by stu-ball** [AirenSoft/OvenMediaEngine#1056] opened 2023-03-05 08:59 UTC
**Describe the bug**
It appears that Docker image airensoft/ovenmediaengine:0.15.1 bootloops on Azure Container Instances.
Previous versions are not affected.

**To Reproduce**
1. Create an Azure Container Instance using an image based on airensoft/ovenmediaengine:0.15.1 (either directly from Docker Hub or a derivative image from another registry including Azure Container Registry).
2. After a minute the container will start reverting to a Waiting state and the count of Pulling/Pulled events will start incrementing (it can run into the hundreds). Logs will not load and connection attempts fail.
![OvenContainerBootloop](https://user-images.githubusercontent.com/34940456/222950789-18102d12-d045-4723-a879-9d26834ed65c.png)
![OvenContainerBootloop2](https://user-images.githubusercontent.com/34940456/222951307-433cd9a7-bc01-40a4-870f-e455ac393c7d.png)

3. The configuration options in Azure do not appear to be a factor. I've tried a lot of different configurations and the result is the same.

**Expected behavior**
All previous versions up to 0.15.0 function normally in Azure Container Instances.

**Server (please complete the following information):**
 - OS: Linux on Azure Container Instances (https://azure.microsoft.com/en-au/products/container-instances/)
 - OvenMediaEngine Version: 0.15.0
 - Branch: latest

**Logs**

[2023-03-05 08:52:55.861] I [OvenMediaEngine:14] Config | config_manager.cpp:239  | Trying to set logfile in directory... (/var/log/ovenmediaengine)
[2023-03-05 08:52:55.875] I [OvenMediaEngine:14] Config | config_manager.cpp:261  | Trying to load configurations... (origin_conf/Server.xml)
[2023-03-05 08:52:55.913] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:23   | OvenMediaEngine v0.15.1 () is started on [SandboxHost-638136022908833413] (Linux x86_64 - 5.10.102.2-microsoft-standard, #1 SMP Mon Mar 7 17:36:34 UTC 2022)
[2023-03-05 08:52:55.916] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:27   | With modules:
[2023-03-05 08:52:55.917] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:28   |   FFmpeg 5.0.1
[2023-03-05 08:52:55.918] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:29   |     Configuration: --prefix=/opt/ovenmediaengine --extra-cflags='-I/opt/ovenmediaengine/include -g ' --extra-ldflags='-L/opt/ovenmediaengine/lib -Wl,-rpath,/opt/ovenmediaengine/lib' --extra-libs=-ldl --enable-shared --disable-static --disable-debug --disable-doc --disable-programs --disable-avdevice --disable-dct --disable-dwt --disable-lsp --disable-lzo --disable-rdft --disable-faan --disable-pixelutils --enable-zlib --enable-libopus --enable-libvpx --enable-libfdk_aac --enable-libopenh264 --enable-openssl --disable-nvdec --disable-nvdec --disable-vaapi --disable-vdpau --disable-cuda-llvm --disable-cuvid --disable-ffnvcodec --disable-everything --disable-fast-unaligned --enable-encoder='libvpx_vp8,libopus,libfdk_aac,libopenh264,mjpeg,png' --enable-decoder='aac,aac_latm,aac_fixed,h264,hevc,opus,vp8' --enable-parser='aac,aac_latm,aac_fixed,h264,hevc,opus,vp8' --enable-network --enable-protocol=tcp --enable-protocol=udp --enable-protocol='rtp,file,rtmp,tls,rtmps' --enable-demuxer='rtsp,flv,live_flv,mp4' --enable-muxer='mp4,webm,mpegts,flv,mpjpeg' --enable-filter='asetnsamples,aresample,aformat,channelmap,channelsplit,scale,transpose,fps,settb,asettb,format'
[2023-03-05 08:52:55.919] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:30   |     libavformat: 59.16.100
[2023-03-05 08:52:55.919] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:31   |     libavcodec: 59.18.100
[2023-03-05 08:52:55.920] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:32   |     libavutil: 57.17.100
[2023-03-05 08:52:55.920] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:33   |     libavfilter: 8.24.100
[2023-03-05 08:52:55.920] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:34   |     libswresample: 4.3.100
[2023-03-05 08:52:55.920] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:35   |     libswscale: 6.4.100
[2023-03-05 08:52:55.920] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:36   |   SRT: 1.4.4
[2023-03-05 08:52:55.920] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:37   |   SRTP: libsrtp2 2.4.2
[2023-03-05 08:52:55.920] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:38   |   OpenSSL: OpenSSL 3.0.7 1 Nov 2022
[2023-03-05 08:52:55.920] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:39   |     Configuration: compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
[2023-03-05 08:52:55.920] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:40   |   JsonCpp: 1.9.3
[2023-03-05 08:52:55.920] I [OvenMediaEngine:14] OvenMediaEngine | banner.cpp:41   |   jemalloc: 5.3.0-0-g54eaed1d8b56b1aa528be3bdd1877e59c56fa90c
[2023-03-05 08:52:55.920] I [OvenMediaEngine:14] OvenMediaEngine | main.cpp:72   | Server ID : a4c4c429-bb36-41ef-86b6-4f13b705e759

**Output stream**
Container 'ovenmediaengine' is in state 'Running'...
(count: 5) (last timestamp: 2023-03-05 08:38:34+00:00) Started container
(count: 4) (last timestamp: 2023-03-05 08:40:27+00:00) Started container
(count: 3) (last timestamp: 2023-03-05 08:43:38+00:00) Started container
(count: 2) (last timestamp: 2023-03-05 08:45:22+00:00) Started container
(count: 15) (last timestamp: 2023-03-05 08:52:40+00:00) pulling image "airensoft/ovenmediaengine@sha256:5903571b843c9d777ba87d23e9a1acce6dff660acbf81e16ee138a6154010216"
(count: 15) (last timestamp: 2023-03-05 08:52:44+00:00) Successfully pulled image "airensoft/ovenmediaengine@sha256:5903571b843c9d777ba87d23e9a1acce6dff660acbf81e16ee138a6154010216"
(count: 1) (last timestamp: 2023-03-05 08:52:55+00:00) Started container

Start streaming logs:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/container/custom.py", line 862, in _stream_container_events_and_logs
    _stream_logs(container_client, resource_group_name, name, container_name, container_group.restart_policy)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/container/custom.py", line 816, in _stream_logs
    lines = log.content.split('\n')
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by getroot** [comment] 2023-03-06 02:27
I have no experience with Azure Container Instance. But airensoft/ovenmediaengine:0.15.1 works fine on other common docker hosts. Is this a bug in OvenMediaEngine images? The 0.15.0 tag and the 0.15.1 tag do not differ in how the image is built.

Do I need to do anything when building a docker image for Azure Container Instance? If you know anything about it, please provide it.

**Comment by getroot** [comment] 2023-03-06 02:30
And what is "Start streaming logs:" ? Isn't this the cause of the problem?

**Comment by stu-ball** [comment] 2023-03-07 11:08
Thanks for taking a look at this one!

I see there's now a 0.15.2 so I was eager to try it out in [Azure Container Instances](https://azure.microsoft.com/en-us/products/container-instances/). Unfortunately, the bootlooping behaviour also affects the new version.

We've deployed almost every single version up to now without issues on Azure Container Instances, and the new updates both work great when we run them locally in Docker.

Unfortunately, we don't really have the expertise in our team to pinpoint the cause, but we'd be very happy to work with you to troubleshoot. [Streaming the logs](https://learn.microsoft.com/en-us/azure/container-instances/container-instances-get-logs) is just one of the diagnostic steps we've tried after we've experienced the issue.

The Roadmap that you've outlined for 2023 looks extremely positive from our perspective, so we're really hoping that we don't end up being locked into 0.15.0 due to this issue.

**Comment by getroot** [comment] 2023-03-07 11:21
Could you please post the full log of OvenMediaEngine when the problem occurred? If OvenMediaEngine was shutting itself down for some reason, there must have been a hint in the logs.

**Comment by stu-ball** [comment] 2023-03-07 11:25
Turns out I might have been premature with that last comment. 

Version 0.15.2 bootlooped three times and then worked. Go figure...

I'll try to do some more thorough testing and report back.

![OvenContainerBootloop3](https://user-images.githubusercontent.com/34940456/223408603-4dcb6b0b-7842-4f04-9218-07daccca40c9.png)

**Comment by stu-ball** [comment] 2023-03-07 11:44
The hard part is that when it gets into the bootlooping state I haven't been able to pull any logs.

**Comment by getroot** [comment] 2023-03-07 11:47
It would be good to get technical support from the Azure team. If they tell you anything please share.

**Comment by stu-ball** [comment] 2023-03-07 11:58
I think you're right to conclude that it looks like an Azure issue. 

I've redeployed 0.15.2 a few times in a row now without any issues so I'm optimistic that we're on the other side of it!

**Comment by getroot** [comment] 2023-03-13 02:08
I think this problem is solved, so I'm closing it. Please reopen if you think further discussion is needed.

**Closed by getroot** 2023-03-13 02:08 UTC
