### ISSUE TITLE
Master commit 5651c10 is broken

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#362] opened 2021-05-07 11:35 UTC
Both @basisbit and I have noticed that the latest 5651c10 commit has a critical issue, crashing OME immediately when a stream starts. The issue is similar to what was reported on #357 but now seems to happen with all streams.

@basisbit I stupidly didn't grab a log before reverting my test environment. Do you have one by chance?

**Comment by getroot** [comment] 2021-05-07 11:38
I am not experiencing the same problem. Maybe a clean build can solve the problem. Have you tried it?

**Comment by getroot** [comment] 2021-05-07 11:39
I haven't tried with docker yet. I'll try with docker too.

**Comment by bchah** [comment] 2021-05-07 11:40
Running a clean build now. I am very excited about these new features you've added @getroot, so there's a lot of testing going on over here in Canada! 👍

**Comment by getroot** [comment] 2021-05-07 11:53
Thank you very much for your contribution. Your quick tests and high-quality reports are of great help to OME's progress.

I just built docker and tested it, but still not experiencing the crash. I used docker's default settings and sent stream with OBS. Will I have to make other settings to reproduce the problem?

docker run -p 1935:1935 -p 4000-4005:4000-4005/udp -p 3333:3333 -p 3478:3478 -p 8080:8080 -p 9000:9000 -p 10000-10010:10000-10010/udp airensoft /ovenmediaengine:dev

**Comment by kwonkeukhan** [comment] 2021-05-07 12:01
@bchah 

If the crash occurs even after a clean build, please send me a log and crash dump file.

**Comment by bchah** [comment] 2021-05-07 12:06
@kwonkeukhan @getroot It crashed immediately, all I did was send RTMP from OBS. Here is the log, I have to go find the dump file...

[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/6441388/ovenmediaengine.log)

**Comment by bchah** [comment] 2021-05-07 12:10
Hmm, I think there might not be a dump file - seeing a 'could not open dump file to write' line in that log.

**Comment by getroot** [comment] 2021-05-07 12:11
@bchah 

@kwonkeukhan  found something in the log file you uploaded. Thank you! It will be resolved soon!

**Comment by bchah** [comment] 2021-05-07 12:15
Thank you @getroot, glad I can help. Since I am doing a manual installation in my environment, do you know where OME is trying to write the dump file? I want to adjust the permissions.

**Comment by kwonkeukhan** [comment] 2021-05-07 12:27
@bchah 
An error occurred in the process of copying the frame.
I've committed, so please test it.

Thanks you

**Comment by bchah** [comment] 2021-05-07 12:28
Thank you @kwonkeukhan, building now!

**Comment by dimiden** [comment] 2021-05-07 12:30
@bchah 
The dump directory is stored in the "current working directory" where the OME is running.
It is usually created where the OME binary is located, but if the "could not open dump file to write" error occurs, it is likely that the directory does not have write permissions.

**Comment by basisbit** [comment] 2021-05-07 12:36
Imho, the location where OME is "installed" should usually not be writable by an OME process. Could the path please be made either configurable or changed to something like `/tmp` or `/var/tmp` if you want it to survive reboots?

**Closed** 2021-05-07 12:57 UTC

**Comment by dimiden** [comment] 2021-05-07 13:14
@basisbit 
Yes, I think that's a good idea. Because I'm pressed by ```HttpServer``` issue (#360), I'll think about 
it in more detail after solving this issue.

**Comment by bchah** [comment] 2021-05-07 13:40
Sorry but I need to reopen this, since I was able to make it crash again. This time the crash occurred when sending in an SRT stream with an invalid signature value. It looks like OBS sends a **LOT** of requests... and also noticed that unlike other crashes, this time OME does not seem to be aware of the fault. Does this log provide any clue? It is from a brand new build of the latest commits:

[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/6441940/ovenmediaengine.log)

**Comment by getroot** [comment] 2021-05-07 13:46
Yes, this is a known issue. If the SRT does not pass the SingedPolicy, the socket must be closed, but there is a slight problem with the socket now.

dimiden is modifying the socket side and it is also associated with #360.

**Comment by bchah** [comment] 2021-05-10 13:49
Hi @getroot I am testing this now... Is there a difference in constructing the URL for SignedPolicy with SRT?

My existing logic for RTMP does not seem to work.

Should this be the value provided to the HMAC function for SRT SignedPolicy?

srt://myserver:9999?streamid=srt://myserver:9999/app/streamname?policy=abc123

**Comment by getroot** [comment] 2021-05-10 14:23
https://airensoft.gitbook.io/ovenmediaengine/v/master/live-source/srt-beta#encoders-and-streamid

Yes. As in the manual above, the streamid of srt must be percent encoded.  Otherwise, because obs truncates the message after &.  The percent encoding result is also printed at the bottom of the output of the misc/generate_signed~~ script.  Just put it after streamid=.

**Comment by getroot** [comment] 2021-05-10 14:28
@bchah After hmac feeding (not before), just generate all urls and do percent encoding!

**Comment by bchah** [comment] 2021-05-10 16:50
Aha! I figured it out.

For the HMAC string, you only use the _streamid_ value, not the complete URL.

I made a pull request to the documentation for this. Now I need a 🍺 😅

@getroot SRT SignedPolicy is working 🤠
