### ISSUE TITLE
OvenMediaEngine | signals.cpp:119 | OME received signal 11 (SIGSEGV), interrupt.

### ISSUE THREAD

**Issue by alex-jhones** [AirenSoft/OvenMediaEngine#171] opened 2020-08-08 05:24 UTC
Hello. @getroot
Again the problem has been reproduced. I will attach the error log.

[crash_20200805.dump.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5041805/crash_20200805.dump.txt)
[ovenmediaengine.log.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5041806/ovenmediaengine.log.txt)

_Originally posted by @alex-jhones in https://github.com/AirenSoft/OvenMediaEngine/issues/164#issuecomment-670529921_

**Comment by getroot** [comment] 2020-08-10 02:04
Thanks for the bug report.
This seems to be a different cause from the previously resolved crash. It seems to be a problem caused by certain transcoding options.
Please share your Server.xml.

**Comment by getroot** [comment] 2020-08-10 04:55
I've tested this with an automatic script player for hours (repeat connect, terminate) but haven't been able to reproduce the same problem. Please provide the following information:

1. Server.xml
2. OBS Settings
3. How to reproduce
4. Can you test again after clean build of the current master branch?

**Comment by alex-jhones** [comment] 2020-08-11 18:19
1. Server.xml
[Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5057032/Server.xml.txt)

2. OBS Settings
![obs](https://user-images.githubusercontent.com/65345605/89899760-b8c06400-dc1d-11ea-9707-18c6250a1e31.jpg)

3. How to reproduce
After setting the attached obs and Server.xml, the problem is reproduced within 5 minutes.
And obs publishes 5 different streams simultaneously.

[crash_20200811.dump.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5058683/crash_20200811.dump.txt)
[ovenmediaengine.log.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5058684/ovenmediaengine.log.txt)
[Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5058685/Server.xml.txt)

4. Can you test again after clean build of the current master branch?
The test was done on the last master branch.

**Comment by getroot** [comment] 2020-08-12 03:12
Unfortunately I've been testing very repeatedly for a long time using your Server.xml and six OBSs, but I haven't been able to reproduce the crash.

But I could find in your logs that our kernel version is different. (Other than that, everything was the same.)

[mine]
`OvenMediaEngine v0.10.7 (v0.10.6-6-g9516cfc) is started on [OME-dev] (Linux x86_64-5.3.0-59-generic, #53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020)`

[Your log]
`OvenMediaEngine v0.10.7 (v0.10.6-6-g9516cfc) is started on [hicys76] (Linux x86_64-4.15.0-109-generic, #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020)`

Could you please check if the problem reproduces after updating the Linux kernel? Thanks for your contribution.

**Comment by kwonkeukhan** [comment] 2020-08-12 08:00
Hello, @alex-jhones .

I tried testing in the same kernel environment, configuration and concurrent publishing.  but, the crash doesn't occur. 

Did you modify the code? Or the same as the master branch source code.

If there is a modified code, can you send me the 'diff' information?

I hope the problemis solved quickly.  thank you. 

**[Testing Kernel Version]**
Linux ubuntu-6cpu-16gb-sg-sin1 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alex-jhones** [comment] 2020-08-12 19:30
@getroot,@kwonkeukhan I ran it on the latest version of ubuntu desktop and didn't modify ome's code either.
![ubuntu](https://user-images.githubusercontent.com/65345605/90056642-2baf0500-dd1a-11ea-99ba-0de720f30d66.jpg)

The problem is reproduced even in the oven player that has not been modified. In order to exclude environmental differences in the experiment, the server/client experimented without modifying the code.

The failure was reproduced by configuring another server to quickly identify the problem. We have sent you the temporarily configured server connection information by e-mail. I hope it helps to reproduce the issue by connecting obs.

**Comment by getroot** [comment] 2020-08-18 14:21
We've done a lot of tests so far.
And I could see that it works well with 10 OBS for 5 days when jemalloc is excluded. So I temporarily removed jemalloc from the default library. (We will do more tests on this.)

Please test with the latest master branch(clean build required) and let me know if your problem is resolved.

**Comment by alex-jhones** [comment] 2020-08-19 21:52
@getroot The current modified version doesn't crash as before (in ovenplayer), but two new issues are observed. One is that the audio does not come out after about 1 to 2 hours, and the second problem is that the oven player that we imported into our development web is currently not playing (it works fine in the old version of OME). We are checking what are the incompatible differences and we will discuss with you again.

**Comment by getroot** [comment] 2020-08-20 04:44
Audio output issues are not related to this patch. Because this patch just doesn't use JEMALLOC
If the audio interruption is a bug, please register this as a separate issue. (But I think this is most likely an encoder problem.)

I will close this issue. Thanks for the contribution.

**Closed by getroot** 2020-08-20 04:44 UTC
