### ISSUE TITLE
LL-DASH not working on Firefox, but working on chrome

### ISSUE THREAD

**Issue by sephentos** [AirenSoft/OvenMediaEngine#319] opened 2021-03-29 19:26 UTC
Hi,

after getting LL-Dash perfectly working with chrome I did not manage to get it working on Firefox.
I'm using latest Dash.js (**v3.2.1**)  (Also tried with various other versions) and my client and server have exactly the **same** timestamp as given from time.akamai.com.
_Using latest OvenPlayer v.0.9.0-2021030518-rev.57fec71._

**Firefox:**

![grafik](https://user-images.githubusercontent.com/35430448/112886371-239dad00-90d2-11eb-8c51-472add745bae.png)

**Chrome:** 

![grafik](https://user-images.githubusercontent.com/35430448/112887866-f5b96800-90d3-11eb-99cc-65c0a7115602.png)

Same results with **OvenPlayer** and **[demo.ovenplayer.com](demo.ovenplayer.com/)**

OvenPlayer is being hosted on a HTTPS-site, OME also have been configured with HTTPS .

Also note that on firefox it's generating many 404 like `https://domain:8081/app/stream/306_audio_ll.m4s` `https://domain:8081/app/stream/262_audio_ll.m4s ` etc.

![grafik](https://user-images.githubusercontent.com/35430448/112890803-978e8400-90d7-11eb-8abe-be0a1a52171a.png)

Chrome (working):

![grafik](https://user-images.githubusercontent.com/35430448/112890916-c147ab00-90d7-11eb-833c-e604b62bd89b.png)

```
OvenPlayer JS:
        {
            file: 'https://domain:8081/app/stream/manifest_ll.mpd',
            type: 'dash',
            lowLatency: true,
            default: true
        }
```

```
...
Server.xml:
                        <DASH>
                                <Port>8080</Port>
                                <TLSPort>8081</TLSPort>
                                <WorkerCount>4</WorkerCount>
                        </DASH>
...
                        <Audio>
                                <Codec>aac</Codec>
                                <Bitrate>128000</Bitrate>
                                <Samplerate>48000</Samplerate>
                                <Channel>2</Channel>
                        </Audio>
                        <Video>
                                <Codec>h264</Codec>
                                <Bitrate>2000000</Bitrate>
                                <Framerate>30</Framerate>
                                <Width>1920</Width>
                                <Height>1080</Height>
                        </Video>
```

OS: Debian 10 (Linux x86_64 - 4.19.0-16-amd64, SMP Debian 4.19.181-1 (2021-03-19))
OME: v0.11.2
OvenPlayer: v.0.9.0-2021030518-rev.57fec71
Dash.js: v3.2.1 (Also tried with various other versions)

Server is not within some kind of VPN or behind a special firewall.
All required ports are open.
Again, keep in mind that it's working perfectly in chrome.

OME log:

```
[2021-03-29 21:24:45.544] I [SegWorker:2079] Monitor | stream_metrics.cpp:119  | A new session has started playing #default#app/stream on the LLDASH publisher. LLDASH(3)/Stream total(3)/App total(3)
[2021-03-29 21:24:46.013] I [SckPoolSegPub:2072] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f940206e0, #34, state: Closed, TCP, 95.223.56.1:31665>) is disconnected
[2021-03-29 21:24:46.487] I [SegPubReq:2083] Monitor | stream_metrics.cpp:144  | A session has been stopped playing #default#app/stream on the LLDASH publisher. Concurrent Viewers[LLDASH(2)/Stream total(2)/App total(2)]
[2021-03-29 21:24:46.487] I [SegPubReq:2083] Monitor | stream_metrics.cpp:144  | A session has been stopped playing #default#app/stream on the LLDASH publisher. Concurrent Viewers[LLDASH(1)/Stream total(1)/App total(1)]
[2021-03-29 21:24:50.420] I [AppWorker:2104] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f94020ad0, #31, state: Closed, TCP, 95.223.56.1:31515>) is disconnected
[2021-03-29 21:24:50.423] I [AppWorker:2104] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f94020ec0, #32, state: Closed, TCP, 95.223.56.1:31592>) is disconnected
[2021-03-29 21:24:55.618] I [AppWorker:2104] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f9401e060, #31, state: Closed, TCP, 95.223.56.1:31688>) is disconnected
[2021-03-29 21:24:56.759] I [SckPoolSegPub:2072] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f9401b350, #31, state: Closed, TCP, 95.223.56.1:31613>) is disconnected
[2021-03-29 21:24:56.760] W [AppWorker:2104] LLDASH | cmaf_stream_server.cpp:126  | Failed to send the chunked data for [#default#app/stream, 10_video_ll.m4s] to <ClientSocket: 0x7f3f9401b350, #31, state: Closed, TCP, 95.223.56.1:31613> (11991 bytes)
[2021-03-29 21:24:56.842] I [SegWorker:2080] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f940177e0, #31, state: Closed, TCP, 95.223.56.1:53902>) is disconnected
[2021-03-29 21:24:56.998] I [SegWorker:2081] HTTPPublisher | segment_publisher.cpp:188  | Segment requested (#default#app/stream/init_audio_ll.m4s) from 95.223.56.1:31598 : Segment number : 0 Duration : 0
[2021-03-29 21:24:56.998] I [SegWorker:2081] Monitor | stream_metrics.cpp:119  | A new session has started playing #default#app/stream on the LLDASH publisher. LLDASH(2)/Stream total(2)/App total(2)
[2021-03-29 21:24:56.999] I [SegWorker:2081] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f94027bb0, #32, state: Closed, TCP, 95.223.56.1:31598>) is disconnected
[2021-03-29 21:24:56.003] I [SegWorker:2082] HTTPPublisher | segment_publisher.cpp:188  | Segment requested (#default#app/stream/init_video_ll.m4s) from 95.223.56.1:21888 : Segment number : 0 Duration : 0
[2021-03-29 21:24:56.003] I [SegWorker:2082] Monitor | stream_metrics.cpp:119  | A new session has started playing #default#app/stream on the LLDASH publisher. LLDASH(3)/Stream total(3)/App total(3)
[2021-03-29 21:24:56.004] I [SegWorker:2082] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f94020180, #31, state: Closed, TCP, 95.223.56.1:21888>) is disconnected
[2021-03-29 21:24:58.488] I [SegPubReq:2083] Monitor | stream_metrics.cpp:144  | A session has been stopped playing #default#app/stream on the LLDASH publisher. Concurrent Viewers[LLDASH(2)/Stream total(2)/App total(2)]
[2021-03-29 21:24:58.488] I [SegPubReq:2083] Monitor | stream_metrics.cpp:144  | A session has been stopped playing #default#app/stream on the LLDASH publisher. Concurrent Viewers[LLDASH(1)/Stream total(1)/App total(1)]
[2021-03-29 21:25:00.404] I [AppWorker:2104] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f9401f730, #31, state: Closed, TCP, 95.223.56.1:21871>) is disconnected
[2021-03-29 21:25:00.408] I [AppWorker:2104] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f94021bb0, #32, state: Closed, TCP, 95.223.56.1:53925>) is disconnected
[2021-03-29 21:25:05.505] I [AppWorker:2104] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f94021fa0, #31, state: Closed, TCP, 95.223.56.1:31526>) is disconnected
[2021-03-29 21:25:05.508] I [AppWorker:2104] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f940225e0, #32, state: Closed, TCP, 95.223.56.1:31622>) is disconnected
[2021-03-29 21:25:10.411] I [AppWorker:2104] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f940295c0, #31, state: Closed, TCP, 95.223.56.1:31699>) is disconnected
[2021-03-29 21:25:15.664] I [AppWorker:2104] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f940287b0, #31, state: Closed, TCP, 95.223.56.1:53930>) is disconnected
[2021-03-29 21:25:20.364] I [AppWorker:2104] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f94028430, #31, state: Closed, TCP, 95.223.56.1:31587>) is disconnected
[2021-03-29 21:25:25.503] I [AppWorker:2104] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f9401bdc0, #31, state: Closed, TCP, 95.223.56.1:22012>) is disconnected
[2021-03-29 21:25:27.187] I [SegWorker:2080] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f94029c00, #32, state: Closed, TCP, 95.223.56.1:21995>) is disconnected
[2021-03-29 21:25:30.392] I [AppWorker:2104] Socket.Server | server_socket.cpp:129  | [#15] [0x55574034dde0] Client(<ClientSocket: 0x7f3f94028d70, #31, state: Closed, TCP, 95.223.56.1:31684>) is disconnected
```

**Comment by sephentos** [comment] 2021-03-29 19:45
Btw:
I also followed the discussion here https://github.com/AirenSoft/OvenMediaEngine/issues/268#issuecomment-772565193 - which did not lead to a fix.

**Comment by basisbit** [comment] 2021-03-30 05:49
@sephentos there is a reason why #268 is still open......
Please close this issue here as it is a duplicate of #268

**Closed** 2021-03-30 15:51 UTC
