### ISSUE TITLE
unlimited memory growth when encoding performance is insufficient

### ISSUE THREAD

**Issue by pandywibowo** [AirenSoft/OvenMediaEngine#989] opened 2023-01-03 04:47 UTC
Server : OS ubuntu 20.04
installation : Docker latest OME

playing multiple stream non abr no error.
Playing single stream with abr no error.
Playing 6 stream with abr there is an error, memory consumable always growing up and after the memory get 90% ome has been killed by system. even tough i have modify Server.xml to disable LLHLS, still not fixed. please fix this bug.

http://194.163.173.200

this is the capture memory consumable always growing up : https://drive.google.com/file/d/1qYwRX8N9-diHZ4Ch6ePavAMJOYNQX99j/view?usp=share_link

Thanks.

**Comment by getroot** [comment] 2023-01-03 05:37
Please upload your Server.xml and ovenmediaengine.log files.

**Comment by pandywibowo** [comment] 2023-01-03 06:50
Hi @getroot , thanks for your response, below is the Server.xml file
`<?xml version="1.0" encoding="UTF-8" ?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	<PrivacyProtection>false</PrivacyProtection>
	
	<StunServer>stun.ovenmediaengine.com:13478</StunServer>

	<Modules>
		
		<HTTP2>
			<Enable>true</Enable>
		</HTTP2>

		<LLHLS>
			<Enable>true</Enable>
		</LLHLS>

		
		<P2P>
			
			<Enable>false</Enable>
			<MaxClientPeersPerHostPeer>2</MaxClientPeersPerHostPeer>
		</P2P>
	</Modules>

	
	<Bind>
		
		
		<Providers>
			
			<RTSPC>
				<WorkerCount>1</WorkerCount>
			</RTSPC>
			<OVT>
				<WorkerCount>1</WorkerCount>
			</OVT>
			
			<RTMP>
				<Port>${env:OME_RTMP_PROV_PORT:1935}</Port>
				<WorkerCount>1</WorkerCount>
			</RTMP>
			<SRT>
				<Port>${env:OME_SRT_PROV_PORT:9999}</Port>
				<WorkerCount>1</WorkerCount>
			</SRT>
			<MPEGTS>
				
				<Port>${env:OME_MPEGTS_PROV_PORT:4000/udp}</Port>
			</MPEGTS>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_WEBRTC_SIGNALLING_PORT:3333}</Port>
					<TLSPort>${env:OME_WEBRTC_SIGNALLING_TLS_PORT:3334}</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>
				<IceCandidates>
					<TcpRelay>${env:OME_WEBRTC_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
					<IceCandidate>*:10006/udp</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			
			<OVT>
				<Port>${env:OME_ORIGIN_PORT:9001}</Port>
				<WorkerCount>1</WorkerCount>
			</OVT>
			<LLHLS>
				
				<Port>${env:OME_LLHLS_STREAM_PORT:3333}</Port>
				<TLSPort>${env:OME_LLHLS_STREAM_TLS_PORT:3334}</TLSPort>
				<WorkerCount>1</WorkerCount>
			</LLHLS>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_WEBRTC_SIGNALLING_PORT:3333}</Port>
					<TLSPort>${env:OME_WEBRTC_SIGNALLING_TLS_PORT:3334}</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>
				<IceCandidates>
					<IceCandidate>*:10000-10005/udp</IceCandidate>
					<TcpRelay>${env:OME_WEBRTC_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			
			<Distribution>ovenmediaengine.com</Distribution>
			
			
			<Host>
				<Names>
					
					<Name>*</Name>
				</Names>
				
			</Host>

			

			

			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						
							
							
								
						

<OutputProfile>
	<Name>webrtc</Name>
	<OutputStreamName>${OriginStreamName}</OutputStreamName>

	<Playlist>
		<Name>webrtc</Name>
		<FileName>webrtc_abr</FileName>
		<Options>
			<WebRtcAutoAbr>true</WebRtcAutoAbr> 
		</Options>
		<Rendition>
			<Name>1080p</Name>
			<Video>1080p</Video>
			<Audio>opus</Audio>
		</Rendition>
		<Rendition>
			<Name>480p</Name>
			<Video>480p</Video>
			<Audio>opus</Audio>
		</Rendition>
		<Rendition>
			<Name>720p</Name>
			<Video>720p</Video>
			<Audio>opus</Audio>
		</Rendition>
	</Playlist>
	
	<Encodes>
		
		<Video>
			<Name>480p</Name>
			<Codec>h264</Codec>
			<Width>640</Width>
			<Height>480</Height>
			<Bitrate>500000</Bitrate>
			<Framerate>30</Framerate>
		</Video>
		<Video>
			<Name>720p</Name>
			<Codec>h264</Codec>
			<Width>1280</Width>
			<Height>720</Height>
			<Bitrate>2000000</Bitrate>
			<Framerate>30</Framerate>
		</Video>
		<Video>
			<Name>1080p</Name>
			<Codec>h264</Codec>
			<Width>1920</Width>
			<Height>1080</Height>
			<Bitrate>5000000</Bitrate>
			<Framerate>30</Framerate>
		</Video>
		
		<Audio>
			<Name>opus</Name>
			<Codec>opus</Codec>
			<Bitrate>128000</Bitrate>
			<Samplerate>48000</Samplerate>
			<Channel>2</Channel>
		</Audio>
	</Encodes>
</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
						<RTSPPull />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
					</Providers>
					<Publishers>
						<AppWorkerCount>16</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						
							
								
							
								
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>
`
and below is the log :
![image](https://user-images.githubusercontent.com/1664887/210311293-bb09e591-acda-439e-b8cf-c5db442f195a.png)

**Comment by getroot** [comment] 2023-01-03 06:56
I need the whole ovenmediaengine.log file, but the capture shows that your system isn't powerful enough to do 24 encodings (6 streams) * (3 video outs + 1 audio out) encodings simultaneously.

**Comment by pandywibowo** [comment] 2023-01-03 07:09
@getroot 
below is the full log, did you mean i need upgrade the memory?

[ome.log](https://github.com/AirenSoft/OvenMediaEngine/files/10334759/ome.log)

**Comment by getroot** [comment] 2023-01-03 07:12
No, you need to upgrade the cpu, not the memory. Since the speed of encoding by the CPU is not 1x, data continues to accumulate in the memory queue. Or you could consider hardware encoding using the GPU.

**Comment by mpisat** [comment] 2023-02-16 03:23
I also have the same issue, it can be reproduced easily with lal tester (from lal media server)
https://github.com/q191201771/lal/blob/master/app/demo/benchrtmpconnect/benchrtmpconnect.go
screen ./benchrtmpconnect -i /root/bbb/bbb_2500kbps_aac.flv -o rtmp://127.0.0.1:1935/app/murat_{i} -r -n 10

I don't even play video, just push 10 streams, with 1080p / 720p / 480p transcoded output on a 8 core i7-9700K at max boost clock (which fails to handle all tbh). Memory usage goes up very high and process is killed. Server ram is 64GB.

**Comment by getroot** [comment] 2023-02-16 05:37
@mpisat I don't think you can do 10*3 transcoding simultaneously on an 8-core CPU. Check your CPU usage.

**Comment by hashworks** [comment] 2023-03-23 14:18
Hm... possible. The server has a lot of free memory (~42 GB), so it may just not return it as nothing needs it. I'll keep an eye on it.

**Comment by hashworks** [comment] 2023-03-24 00:02
Nah, this is definitely not normal.

![image](https://user-images.githubusercontent.com/2362091/227390386-b956a0b9-e69c-4cbb-b81c-a9fde6523a7a.png)

I started a small stream at 22:43, which generated some CPU usage and started to fill the memory. At 22:50 the stream died. Since then the memory has not been freed. The system remains under high load.

![image](https://user-images.githubusercontent.com/2362091/227387083-c0e4180c-5806-4c14-a00f-e7b9f9b643ad.png)

![image](https://user-images.githubusercontent.com/2362091/227387073-5664e1eb-dc78-46cc-8cbc-07f8170d1bbd.png)

![image](https://user-images.githubusercontent.com/2362091/227387028-82b0122c-3be1-4ec4-a7fe-011c9b9607e9.png)

I have some error that spams my log:
```
[2023-03-23 22:50:12.899] W [Rescaler:3652353] ov.Queue | queue.h:268  | [0x7fab8c606a18] Input queue of Encoder. track(4) codec(h264/27) size has exceeded the threshold: queue: 10113, threshold: 120, peak: 10113
[2023-03-23 22:50:12.930] W [Rescaler:3652361] ov.Queue | queue.h:268  | [0x7fab8c625618] Input queue of Encoder. track(2) codec(h264/27) size has exceeded the threshold: queue: 10114, threshold: 120, peak: 10114
[2023-03-23 22:50:17.832] W [Rescaler:3652357] ov.Queue | queue.h:268  | [0x7fab8c7fe818] Input queue of Encoder. track(3) codec(h264/27) size has exceeded the threshold: queue: 10250, threshold: 120, peak: 10250
[2023-03-23 22:50:17.864] W [Rescaler:3652349] ov.Queue | queue.h:268  | [0x7fab8c605218] Input queue of Encoder. track(1) codec(h264/27) size has exceeded the threshold: queue: 10249, threshold: 120, peak: 10249
[2023-03-23 22:50:17.912] W [Rescaler:3652353] ov.Queue | queue.h:268  | [0x7fab8c606a18] Input queue of Encoder. track(4) codec(h264/27) size has exceeded the threshold: queue: 10249, threshold: 120, peak: 10250
[2023-03-23 22:50:17.937] W [Rescaler:3652361] ov.Queue | queue.h:268  | [0x7fab8c625618] Input queue of Encoder. track(2) codec(h264/27) size has exceeded the threshold: queue: 10285, threshold: 120, peak: 10285
```

No log messages since 22:50.

<details> 
  <summary>Server.xml</summary>

```
?xml version="1.0" encoding="UTF-8"?>

<Server version="8">
    <Name>OvenMediaEngine</Name>
    <Type>origin</Type>
    <IP>*</IP>
    <PrivacyProtection>false</PrivacyProtection>

    <Bind>
        <Providers>
            <RTMP>
                <Port>1935</Port>
                <WorkerCount>1</WorkerCount>
            </RTMP>
        </Providers>

        <Publishers>
            <WebRTC>
                <Signalling>
                    <Port>3333</Port>
                    <WorkerCount>4</WorkerCount>
                </Signalling>
                <IceCandidates>
                    <IceCandidate>*:10000-10005/udp</IceCandidate>
                    <TcpRelay>*:53478</TcpRelay>
                    <TcpForce>true</TcpForce>
                    <TcpRelayWorkerCount>1</TcpRelayWorkerCount>
                </IceCandidates>
            </WebRTC>
        </Publishers>
    </Bind>

    <VirtualHosts>
        <VirtualHost>
            <Name>default</Name>

            <Host>
                <Names>
                    <Name>*</Name>
                </Names>
            </Host>

            <!-- ./signed_policy_generator.sh [HMAC_KEY] [BASE_URL] [SIGNATURE_QUERY_KEY_NAME] [POLICY_QUERY_KEY_NAME] [POLICY] -->
            <SignedPolicy>
                <PolicyQueryKeyName>policy</PolicyQueryKeyName>
                <SignatureQueryKeyName>signature</SignatureQueryKeyName>
                <SecretKey>redacted</SecretKey>

                <Enables>
                    <Providers>rtmp</Providers>
                </Enables>
            </SignedPolicy>

            <Applications>
                <Application>
                    <Name>live</Name>
                    <Type>live</Type>
                    <OutputProfiles>
                        <OutputProfile>
                            <Name>bypass_stream</Name>
                            <OutputStreamName>${OriginStreamName}</OutputStreamName>
                            <Playlist>
                                <Name>Quality Profiles</Name>
                                <FileName>abr</FileName>
                                <Options>
                                    <WebRtcAutoAbr>false</WebRtcAutoAbr>
                                </Options>
                                <Rendition>
                                    <Name>Original</Name>
                                    <Video>bypass_video</Video>
                                    <Audio>opus</Audio>
                                </Rendition>
                                <Rendition>
                                    <Name>7MBits</Name>
                                    <Video>7mbits_h264</Video>
                                    <Audio>opus</Audio>
                                </Rendition>
                                <Rendition>
                                    <Name>5MBits</Name>
                                    <Video>5mbits_h264</Video>
                                    <Audio>opus</Audio>
                                </Rendition>
                                <Rendition>
                                    <Name>2MBits</Name>
                                    <Video>2mbits_h264</Video>
                                    <Audio>opus</Audio>
                                </Rendition>
                            </Playlist>
                            <Encodes>
                                <Video>
                                    <Name>bypass_video</Name>
                                    <Bypass>true</Bypass>
                                </Video>
                                <Audio>
                                    <Name>opus</Name>
                                    <Codec>opus</Codec>
                                    <Bitrate>256000</Bitrate>
                                    <Samplerate>48000</Samplerate>
                                    <Channel>2</Channel>
                                </Audio>
                                <Video>
                                    <Name>10mbits_h264</Name>
                                    <Codec>h264</Codec>
                                    <Bitrate>10000000</Bitrate>
                                </Video>
                                <Video>
                                    <Name>7mbits_h264</Name>
                                    <Codec>h264</Codec>
                                    <Bitrate>7000000</Bitrate>
                                </Video>
                                <Video>
                                    <Name>5mbits_h264</Name>
                                    <Codec>h264</Codec>
                                    <Bitrate>5000000</Bitrate>
                                </Video>
                                <Video>
                                    <Name>2mbits_h264</Name>
                                    <Codec>h264</Codec>
                                    <Bitrate>2000000</Bitrate>
                                </Video>
                            </Encodes>
                        </OutputProfile>
                    </OutputProfiles>
                    <Providers>
                        <RTMP />
                    </Providers>
                    <Publishers>
                        <AppWorkerCount>1</AppWorkerCount>
                        <StreamWorkerCount>8</StreamWorkerCount>
                        <WebRTC>
                            <Timeout>10000</Timeout>
                            <Rtx>false</Rtx>
                            <Ulpfec>false</Ulpfec>
                            <JitterBuffer>false</JitterBuffer>
                        </WebRTC>
                    </Publishers>
                </Application>
            </Applications>
        </VirtualHost>
    </VirtualHosts>
</Server>

```

</details>

**Comment by getroot** [comment] 2023-03-24 01:38
@hashworks 

How many cores does your server have?

That is also expected result. The log warning that the queue size keeps increasing means that the encoding speed is slow, so the 1x speed is not coming out. As a result, frames continue to accumulate in the queue.

Your CPU seems to have room. Then you can assign more threads to the encoding profile. Or change the preset to fast or faster.

Encode Thread Count default : MIN(MAX(4, CPU_CORE_COUNT/3), 8)
Preset default : medium

```
<Encodes>
     <Video>
       <ThreadCount>8</ThreadCount>
       <Preset>faster</Preset>
```

https://airensoft.gitbook.io/ovenmediaengine/transcoding#video

**Comment by hashworks** [comment] 2023-03-24 02:34
Yes, I've read in similar issues that the 'size has exceeded the threshold' error is the result of a lack of performance. But that is just a symptom of the main issue: the high memory usage. I think there is a memory leak here. The system can handle the encodes just fine under normal circumstances (as you said, the Ryzen 3600 has room).

**Comment by getroot** [comment] 2023-03-24 03:38
@hashworks 

Insufficient encoding speed will cause high memory usage. OvenMediaEngine has queues in several places such as decode queue and encode queue. After decoding is completed, decoded frame are entered to the Encode Queue, and the codec(openh264) gets frames from the Encode Queue and encodes them. If the codec is slow, frames continue to pile up in the encode queue, which causes memory usage growth. That's what your log says. Since your CPU has room, increasing the ThreadCount of your encoder will most likely solve your problem. 

I think you seem to think of cause and effect in reverse. Please correct me if I'm misunderstanding your thinking.

**Comment by hashworks** [comment] 2023-03-24 17:48
Ah, thanks for the explanation of the log message.

Let's ignore the encoding performance and focus on the memory issue. While it makes sense to queue frames that are waiting to be encoded, there should be a limit after which they are discarded. It doesn't make sense to store 40 GB of old frames, especially if the stream has ended long ago. Can one specify that old frames are dropped after a sensible amount has queued up in memory?

Yesterday's memory hog of OME got so bad, that I wasn't able to SIGKILL the process, systemd refused to respond to commands and I had to reset the system using IPMI. I'll have to set up some [resource control for the systemd unit](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#MemoryMax=bytes) so the OOM Killer restarts it after it has passed a sensible amount of memory.

**Comment by getroot** [comment] 2023-03-27 02:06
@hashworks 

Yes, you are right.
I also think there should be a maximum limit for Queue.
However, the drop algorithm has a lot to consider. I will consider the policy that can most efficiently drop packets in the queue. For example, if a key frame is dropped, all the frames up to the next key frame are not used, so it would be efficient to drop them all. Also, if the queue threshold is exceeded due to momentary network congestion, the congestion in the queue will be released soon, so it is not good to drop it at this time. Most importantly, dropping from the queue will result in playback stuck. It seems that we need a way to inform this effectively.

**Comment by Keukhan** [comment] 2023-05-09 12:58
@pandywibowo 

Added experimental features. It is still an unofficial feature, and can be tested on the master branch.
This is a method to avoid forced shutdown of the system due to memory increase.

[Experimental Feature] Delete Lazy Stream - https://github.com/AirenSoft/OvenMediaEngine/discussions/1221

Thanks

**Comment by getroot** [comment] 2023-06-19 11:08
This issue has been resolved. If the problem reproduces, please reopen.

**Closed by getroot** 2023-06-19 11:08 UTC
Labels: patched, improvement, long-term fix
