### ISSUE TITLE
Signed Policy ignores "stream_expire" time

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#342] opened 2021-04-18 00:11 UTC
**Describe the bug**

With a signed stream key, the "url_expire" policy property works perfectly, but the "stream_expire" property is ignored by OME and the stream continues playing even after the "stream_expire" time. 

**To Reproduce**

Sign a stream key with a policy like
{"url_expire":7245594130000, "stream_expire": 7245594130000}
In that example it is more than 100 years from now, but you get the idea 😄 

Playback continues even after the stream_expire time.

**Expected behavior**

At the time specified in milliseconds since UNIX epoch for 'stream_expire', the stream should stop and the encoder / RTMP transmission should fail.

**Logs**

(Server name and IP are changed - sorry about all the thumbnail requests!)
[ome.log](https://github.com/AirenSoft/OvenMediaEngine/files/6330269/ome.log)

**Server (please complete the following information):**

 - OS: Ubuntu 18.04
 - OvenMediaEngine Version: 0.11.2
 - Branch: dev (about 1 week ago)

**Player (please complete the following information):**

Any

**Comment by getroot** [comment] 2021-05-04 04:19
I have implemented this feature in RTMP and committed it. Could you please check if the function is working properly? Thanks for reporting the bug.

From now on, I will add SignedPolicy feature to SRT and WebRTC Provider as well.

**Comment by bchah** [comment] 2021-05-07 15:44
@getroot I can confirm this is working in RTMP 🥇  

But I will leave this issue open for the SRT and WebRTC providers, since SignedPolicy is not fully implemented with them yet.

**Comment by getroot** [comment] 2021-05-10 12:22
Since the recent commit, I have confirmed that SignedPolicy works properly in SRT and WebRTC Provider. Could you please check if this solved your problem as well?

**Comment by bchah** [comment] 2021-09-28 14:18
Hi @getroot, I am reopening this issue to remark that SignedPolicy does not seem to work with HLS.

I notice that HLS streams are working without being allowed by the signed policy. My assumption is that HLS would need to be added to the SignedPolicy -> Enables -> Publishers property of the Server config, like this:

`<Enables>
   <Publishers>webrtc, hls</Publishers>
</Enables>`

In testing, I can remove the policy and signature from my HLS URL and it still works fine in VLC, even when HLS is not enabled for signed policy.

I haven't tested SignedPolicy with DASH, but from a security standpoint I think it's very important that the signed policy applies to *all* providers and publishers.

Can you please confirm if this is expected behaviour? Thank you 👍

**Comment by bchah** [comment] 2021-09-28 14:19
Ah, it will not allow me to reopen this issue. Please let me know if I should create a new issue or if you can re-open this one, thanks.

**Comment by getroot** [comment] 2021-09-29 14:56
This code hasn't changed recently.
Could you please test if it is because there is a space before the hls text in <Publishers>webrtc, hls</Publishers> ? Sometimes we forget to add code to remove spaces.

**Comment by getroot** [comment] 2021-10-05 14:35
@bchah 
As expected, whitespace before the HLS string was the problem. I've fixed it to remove whitespace, even if it's there, so that users don't get confused.

**Closed by getroot** 2021-10-05 14:35 UTC
Labels: bug

**Comment by bchah** [comment] 2021-10-05 16:44
Thank you @getroot - I may have misunderstood how this feature is intended. My impression was that SignedPolicy is a global setting, and would block any providers or publishers that were not enabled. My updated understanding is that you need to specify the same publishers and providers you have enabled in the config, or they will not get any security benefit.

e.g.

`<Enables> <Publishers>webrtc,hls</Publishers> </Enables>` = SignedPolicy required for WebRTC and HLS
`<Enables> <Publishers>webrtc</Publishers> </Enables>` = SignedPolicy required for WebRTC, no restrictions on HLS

With SignedPolicy enabled for WebRTC only, I can create an HLS URL with an unsigned stream key like so:

![Screen Shot 2021-10-05 at 12 36 51 PM](https://user-images.githubusercontent.com/33604674/136065565-2f68817c-6aab-4cd5-a2e5-fb70349b5896.jpg)

Am I now understanding this correctly or did you intend for the setting to be global? I trust your design choice either way 😃

**Comment by getroot** [comment] 2021-10-06 03:16
@bchah 
As you understand SignedPolicy applies to publisher and provider you set in <Enables>. A provider or publisher that does not have SingendPolicy enabled is not blocked, just signedpolicy is not applied. If you want SignedPolicy to be applied to all Providers and Publishers, you have to set it as follows.

```
<SignedPolicy>
	<PolicyQueryKeyName>policy</PolicyQueryKeyName>
	<SignatureQueryKeyName>signature</SignatureQueryKeyName>
	<SecretKey>aKq#1kj</SecretKey>

	<Enables>
		<Providers>rtmp,webrtc,srt</Providers>
		<Publishers>webrtc,hls,dash,lldash</Publishers>
	</Enables>
</SignedPolicy>
```
