### ISSUE TITLE
Rtmp input protection 

### ISSUE THREAD

**Issue by Swiftgti** [AirenSoft/OvenMediaEngine#200] opened 2020-09-29 02:41 UTC
Hi how do you protect the rtmp input of the application so other people don’t publish on the application without permission? 
YouTube and similars use a key? 
Where do you configure this key in oven media ?
 Without any protection is useless for the real world and production environment. Thanks

**Comment by getroot** [comment] 2020-10-02 23:34
I think I need this feature. Your request is probably related to #42. We plan to implement this feature soon, but so far it has been postponed to implement a higher priority feature. For reference, others were using a solution by putting NGINX in front of OME.

**Comment by getroot** [comment] 2020-11-17 09:38
Take a look at this feature. This can solve your problem.

https://airensoft.gitbook.io/ovenmediaengine/signedpolicy

**Comment by getroot** [comment] 2020-11-17 09:47
This issue is a duplicate of #68, so we will continue to discuss it here. Close this issue.

**Closed by getroot** 2020-11-17 09:47 UTC
