### ISSUE TITLE
Dash Audio segments are available, but not video segments.

### ISSUE THREAD

**Issue by juanuys** [AirenSoft/OvenMediaEngine#372] opened 2021-05-20 11:25 UTC
**Describe the bug**

Audio segments are available, but not video segments.

**To Reproduce**

Streaming webcam from OBS into OME.
OME run with:

```
docker run -p 1935:1935 -p 4000-4005:4000-4005/udp -p 3333:3333 -p 3478:3478 -p 8080:8080 -p 9000:9000 -p 10000-10010:10000-10010/udp airensoft/ovenmediaengine:0.11.3
```
Using demo Oven player at http://demo.ovenplayer.com/#sources=%5B%7B%22id%22%3A0%2C%22file%22%3A%22http%3A%2F%2F172.31.240.1%3A8080%2Fapp%2Fstream%2Fmanifest.mpd%22%2C%22type%22%3A%22dash%22%7D%5D&lowLatency=false&liveDelay=false

**Expected behavior**

Video segments should be found, and video should be visible in player.

**Logs**
Please upload the entire OvenMediaEngine.log. You may delete important personal information.

I exec'd into the running Docker container, and ran this, but it found nothing:
```
find / -name OvenMediaEngine.log
```

Here's an excerpt from the terminal:

```
[2021-05-20 11:03:56.359] I [SegWorker:52] Socket.Server | server_socket.cpp:129  | [#44] [0x560aa09c7540] Client(<ClientSocket: 0x7f7af00383f0, #75, state: Closed, TCP, 172.17.0.1:37138>) is disconnected
[2021-05-20 11:03:56.364] W [SegWorker:53] HTTPPublisher | segment_publisher.cpp:169  | Could not find a segment for DASH Publisher [#default#app/stream, 128_audio.m4s]
[2021-05-20 11:03:56.364] I [SegWorker:53] Socket.Server | server_socket.cpp:129  | [#44] [0x560aa09c7540] Client(<ClientSocket: 0x7f7af00387e0, #75, state: Closed, TCP, 172.17.0.1:37142>) is disconnected
[2021-05-20 11:03:56.410] W [SegWorker:50] HTTPPublisher | segment_publisher.cpp:169  | Could not find a segment for DASH Publisher [#default#app/stream, 125_video.m4s]
[2021-05-20 11:03:56.410] I [SegWorker:50] Socket.Server | server_socket.cpp:129  | [#44] [0x560aa09c7540] Client(<ClientSocket: 0x7f7af0038bd0, #75, state: Closed, TCP, 172.17.0.1:37146>) is disconnected
[2021-05-20 11:03:56.483] W [SegWorker:51] HTTPPublisher | segment_publisher.cpp:169  | Could not find a segment for DASH Publisher [#default#app/stream, 126_video.m4s]
```

**Server (please complete the following information):**
 - OS: Windows 10, with Docker running WSL2 (docker command run from Ubuntu)
 - OvenMediaEngine Version:  v0.11.3
 - Branch: ?

**Player (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser: Firefox 88.0.1 (64-bit)
 - Version: http://demo.ovenplayer.com

**Additional context**

Spot the 404 on each video segment, but the audio segments have 200  (HTTP OK).
Dash also doesn't work from VLC, but HLS does.

![image](https://user-images.githubusercontent.com/54897285/118969515-09ab7880-b965-11eb-81bc-3581d64b7283.png)

**Comment by getroot** [comment] 2021-05-20 11:41
The log of OvenMediaEngine is inside the docker container. You can access it by connecting to the bash shell with docker exec.

https://docs.docker.com/engine/reference/commandline/exec/

Does WebRTC or HLS play well? Several MPEG-DASH-related bugs have been patched since 0.11.3, and the next version will be released soon. If you want to use it first, test it using the master branch.

**Comment by juanuys** [comment] 2021-05-20 12:45
I'll try the latest engine, thanks. Here's the log: http://sprunge.us/svVSxj

BTW, Your Github issue template calls it `OvenMediaEngine.log`, but it's actually `ovenmediaengine.log`.

I should have instead used `iname` in the find command inside the container:

```
# find / -iname OvenMediaEngine.log
/var/log/ovenmediaengine/ovenmediaengine.log
```

**Comment by juanuys** [comment] 2021-05-20 13:13
Same issue with `airensoft/ovenmediaengine:dev`.

Here's the log: http://sprunge.us/DYDaFf

![image](https://user-images.githubusercontent.com/54897285/118984637-9c541380-b975-11eb-994e-55793ab1299c.png)

**Comment by juanuys** [comment] 2021-05-20 13:18
BTW, this might be useful:

| Time source | Timestamp |
| ---- | ---- |
| http://time.akamai.com/?iso&ms | 2021-05-20T13:16:12.689Z |
| `date` in container | Thu May 20 13:16:07 UTC 2021 |

Container time is 5 seconds earlier.

**Comment by getroot** [comment] 2021-05-20 13:22
We are committing the functionality to embed time server into OME today. And that feature will be applied to the docker image soon.

**Comment by juanuys** [comment] 2021-05-20 13:29
> 
> 
> We are committing the functionality to embed time server into OME today. And that feature will be applied to the docker image soon.

That's great, thanks. I was just looking at adding it myself and sending a PR later :)

**Comment by juanuys** [comment] 2021-05-20 14:03
Upping the DASH segment duration to 10 also smoothed over the 5 second time difference:

**Comment by getroot** [comment] 2021-05-20 14:40
0.12.0 has been released. The problem caused by time difference when playing MPEG-DASH is now resolved using the built-in time server. Please check if your problem is resolved.

**Comment by juanuys** [comment] 2021-05-20 14:58
HLS works, but Dash is still problematic:

```
[2021-05-20 14:56:25.037] I [SegWorker:51] Monitor | stream_metrics.cpp:119  | A new session has started playing #default#app/stream on the DASH publisher. DASH(1)/Stream total(1)/App total(1)
[2021-05-20 14:56:25.052] I [SegWorker:52] HTTPPublisher | segment_publisher.cpp:188  | Segment requested (#default#app/stream/65_audio.m4s) from 172.17.0.1:46518 : Segment number : 65 Duration : 4
[2021-05-20 14:56:25.066] I [SegWorker:53] HTTPPublisher | segment_publisher.cpp:188  | Segment requested (#default#app/stream/66_audio.m4s) from 172.17.0.1:46522 : Segment number : 66 Duration : 5
[2021-05-20 14:56:25.070] I [SegWorker:54] HTTPPublisher | segment_publisher.cpp:188  | Segment requested (#default#app/stream/67_audio.m4s) from 172.17.0.1:46526 : Segment number : 67 Duration : 4
[2021-05-20 14:56:25.084] I [SegWorker:51] HTTPPublisher | segment_publisher.cpp:188  | Segment requested (#default#app/stream/68_audio.m4s) from 172.17.0.1:46530 : Segment number : 68 Duration : 4
[2021-05-20 14:56:25.340] W [SegWorker:52] HTTPPublisher | segment_publisher.cpp:169  | Could not find a segment for DASH Publisher [#default#app/stream, 65_video.m4s]
[2021-05-20 14:56:25.354] W [SegWorker:53] HTTPPublisher | segment_publisher.cpp:169  | Could not find a segment for DASH Publisher [#default#app/stream, 66_video.m4s]
[2021-05-20 14:56:28.981] W [SegWorker:54] HTTPPublisher | segment_publisher.cpp:169  | Could not find a segment for DASH Publisher [#default#app/stream, 69_audio.m4s]
[2021-05-20 14:56:46.386] I [SegPubReq:55] Monitor | stream_metrics.cpp:144  | A session has been stopped playing #default#app/stream on the DASH publisher. Concurrent Viewers[DASH(0)/Stream total(0)/App total(0)]
```

The idea I had before was setting the container's datetime using NTP - what do you think?

**Comment by juanuys** [comment] 2021-05-20 15:04
I think I might be plagued by [this issue](https://github.com/microsoft/WSL/issues/5324). Let me try a reboot and see if the problem goes away.

**Comment by juanuys** [comment] 2021-05-20 15:17
Host and container now agree on time, but the problem persists.

**Comment by dimiden** [comment] 2021-05-21 09:17
@juanuys 
As @getroot answered above, HLS plays well, so I don't think it's a problem with the packetizer of DASH.
Could you try again after adding the ```<UTCTiming>``` element referring to the [Server.xml of 0.12.0](https://github.com/AirenSoft/OvenMediaEngine/blob/master/misc/conf_examples/Server.xml) to reduce the number of cases where the problem occurs?

**Comment by juan-offworld** [comment] 2021-05-21 09:47
Here is an excerpt from the origin conf's Server.xml (in 0.12.0 docker container):

```
                                                <DASH>
                                                        <SegmentDuration>5</SegmentDuration>
                                                        <SegmentCount>3</SegmentCount>
                                                        <CrossDomains>
                                                                <Url>*</Url>
                                                        </CrossDomains>
                                                        <UTCTiming />
                                                </DASH>
                                                <LLDASH>
                                                        <SegmentDuration>5</SegmentDuration>
                                                        <CrossDomains>
                                                                <Url>*</Url>
                                                        </CrossDomains>
                                                        <UTCTiming />
                                                </LLDASH>
```

I can still quickly try the new UTCTiming tag and get back to you?

**Comment by dimiden** [comment] 2021-05-21 09:54
@juan-offworld
I would appreciate it if you could check the two things below.

1. Please attach the complete log (```ovenmediaengine.log```).
2. A screenshot of network tab in the browser.
  - Like the screenshot you posted in the comment above, please attach the result of running on v0.12.0.
  - This is to check if time API request to OME is successfully.

**Comment by juanuys** [comment] 2021-05-21 10:33
@dimiden thanks for the reply. I ran a test with 0.12.0 (Docker) and this Server.xml: http://sprunge.us/qNeZOz

HLS works, but Dash does not (missing segments).

Here's the log: http://sprunge.us/NoHXJL

Here's the devtools:
![image](https://user-images.githubusercontent.com/54897285/119123656-afbfb700-ba27-11eb-9c66-d3e183de32b5.png)

**Comment by dimiden** [comment] 2021-05-21 13:16
@juanuys 
Thank you for the detailed information.
As I checked the log you attached, the first video frame is coming in about 8 seconds later than the audio.
Currently, DASH packetizer of OME based on duration rather than PTS-based, so if the A/V sync is different more than segmentation duration, video playback will fail.

So, If you are using OBS, I recommend that you try by modifying only the following values for the default options:

- Go to the "Output" tab and set the following entries:
    - Output Mode: Advanced
    - Keyframe Interval: 1
    - Profile: baseline
    - Tune: zerolatency

![image](https://user-images.githubusercontent.com/4264558/119142631-b2e79100-ba81-11eb-806d-e4d4fbfc131f.png)

**Comment by getroot** [comment] 2021-06-08 11:32
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.

**Closed by getroot** 2021-06-08 11:32 UTC
