### ISSUE TITLE
No request is sent when closing LLHLS

### ISSUE THREAD

**Issue by albeliakov** [AirenSoft/OvenMediaEngine#845] opened 2022-08-09 10:37 UTC
AdmissionWebhooks doesn't send request with "closing" status when llhsl connection is closed. But when the connection is opened, the status "opening" is sent.

**Comment by getroot** [comment] 2022-08-09 12:15
This is a feature that hasn't been implemented yet.

The closing event of AdmissionWebhooks is not an officially included feature, but a feature implemented by one contributor posting a PR.

https://github.com/AirenSoft/OvenMediaEngine/pull/677

In LLHLS, this is very complicated to implement. When LLHLS runs over HTTP/2, multiple LLHLS sessions can be connected over one connection, and in HTTP/1.1, one LLHLS session can be connected over multiple connections.

This could be implemented later, but not in the near future because I've been too busy lately. Any PR from another contributor would be very welcome.

**Comment by albeliakov** [comment] 2022-08-09 12:18
@getroot Thanks for the answer.
Is redirection by url_new implemented for LLHLS?

**Comment by getroot** [comment] 2022-08-09 12:20
In my tests new_url (not url_new) worked fine.

**Comment by albeliakov** [comment] 2022-08-09 12:44
@getroot I get this error when using new_url with llhls.
Incoming: `rtmp://xxx.xx.xx.xx:3333/app/streamkey1`
new_url: `http://xxx.xx.xx.xx:3333/app/streamkey1l/llhls.m3u8`
Outcoming: `http://xxx.xx.xx.xx:3333/app/new_url/llhls.m3u8`
```
[2022-08-09 12:35:51.560] E [SPRtcSig-T3333:9] Orchestrator | orchestrator.cpp:660  | Could not find Origin for the stream: [#default#app/new_url]
[2022-08-09 12:35:51.560] E [SPRtcSig-T3333:9] LLHLS Publisher | llhls_publisher.cpp:325  | Could not pull the stream : new_url
```

**Comment by getroot** [comment] 2022-08-09 12:50
Test your control server's HTTP response with curl and let me know. 

https://airensoft.gitbook.io/ovenmediaengine/access-control/admission-webhooks#format-1

**Comment by albeliakov** [comment] 2022-08-09 13:16
@getroot
```
curl -d ' 
{ "client": 
    { "address": "172.xx.xx.xxx", "port": 52736}, 
  "request": 
    { "direction": "outgoing", "protocol": "LLHLS", "status": "opening", "url": "http://172.xx.xx.xx:3333/app/new_url/llhls.m3u8", 
  "time": "2022-08-09T12:29:33.616+00:00" }
 }' 
-H 'Content-Type: application/json' -H "X-OME-Signature: 1db8cdc5107c2cf341a55bcf10760ac7462dbfa6" -X POST http://127.0.0.1:9595/v1/admission
```
Response
`{"allowed": true, "new_url": "http://172.xx.xx.xx:3333/app/streamkey1/llhls.m3u8", "reason": "authorized"}`

**Comment by getroot** [comment] 2022-08-11 05:11
I was able to reproduce your problem. I will fix this issue soon.
Please change the title of this issue or create a new issue.

**Comment by getroot** [comment] 2022-08-11 06:17
I just patched this issue and committed it.
You can test it with the master branch. Please check if your problem is solved.

**Comment by albeliakov** [comment] 2022-08-11 07:30
@getroot I used airensoft/ovenmediaengine:dev. The problem is not solved.

**Comment by getroot** [comment] 2022-08-11 07:32
You may have used a locally cached airensoft/ovenmediaengine:dev image, so try pulling it again. In my environment it works fine with no issues.

**Closed** 2022-08-11 07:44 UTC
Labels: help

**Comment by getroot** [comment] 2022-08-11 07:46
Please change the title so others can find this issue.
