### ISSUE TITLE
Errors when running latest build

### ISSUE THREAD

**Issue by valkoivanov** [AirenSoft/OvenMediaEngine#11] opened 2019-01-09 18:25 UTC
Hello, trying to run latest version
![screenshot from 2019-01-09 20-01-37](https://user-images.githubusercontent.com/46536048/50919536-bb5c4580-144b-11e9-8c95-8a078ecc857e.png)
![screenshot from 2019-01-09 20-03-29](https://user-images.githubusercontent.com/46536048/50919540-bd260900-144b-11e9-91da-0d2bedadc4cc.png)
[Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/2742066/Server.xml.txt)

 of OME got following error:

[01-09 20:10:54.656] I 8197 MediaRouter | media_router.cpp:61   | Media router is started.
[01-09 20:10:54.658] E 8197 Socket | socket.cpp:186  | [0x5590c1ea5660] [#7] Could not bind to [v4] 0.0.0.0:80 (-1)
[01-09 20:10:54.658] E 8197 Socket | socket.cpp:638  | [#2] Invalid state: 1 (expected: _state(1) == SocketState::Listening)

The above error happens with and without Apache2 service running.

When started OBS streaming got following error (multiple times):

[01-09 20:14:17.629] E 8513 TranscodeCodec | transcode_codec_dec_avc.cpp:78   | DecodeFrameNoDelay failed, state=4,len=61
[01-09 20:14:17.652] E 8513 TranscodeCodec | transcode_codec_dec_avc.cpp:78   | DecodeFrameNoDelay failed, state=4,len=37
...

I'm hoping you can help me with this issue

Regards,

Valko Ivanov

**Comment by sfreet** [comment] 2019-01-10 02:33
1. Are you sure that your system does not use port 80?
Please check your port with **"netstat -na | grep :80"** or **"lsof -i :80"** command in terminal
For sure, you can change it another port as follows
```
<HLS>
	<IP>192.168.0.50</IP>
	<Port>9999</Port>
</HLS>
<DASH>
	<IP>192.168.0.50</IP>
	<Port>9999</Port>
</DASH>
```

2. What is the encoding profile of OBS studio setting? (main or high or baseline)
If it's not a baseline, try changing it to baseline.

**Comment by dengwoadeng** [comment] 2019-01-15 06:11
Hello, I also trying to run latest version.The same error has occurred and  my system does not use port 80.
at the same time `Get offer sdp failed. Cannot find stream (live/1234_o)`.

![image](https://user-images.githubusercontent.com/34929719/51161861-0a343000-18cf-11e9-9fb6-bad4c9eef6bb.png)

this is my system file
[Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/2758211/Server.xml.txt)

**Comment by sfreet** [comment] 2019-01-21 02:13
I close this issue. If the issue is not resolved, please let me know again.

**Closed** 2019-01-21 02:13 UTC

**Comment by crcorrea** [comment] 2020-03-21 15:53
HI,  socket error when starting ovenmediaengine
![2020-03-21](https://user-images.githubusercontent.com/19252937/77230433-e0ca0080-6b72-11ea-8c92-383d2ee73310.png)

**Comment by dimiden** [comment] 2020-03-24 03:26
@crcorrea 
Other daemons using ports 1935 and 80 seem to be running.
Execute the following command to terminate the process using the port or change the port used by OvenMediaEngine.

```
$ sudo netstat -plnt | grep -e ":1935" -e ":80"
tcp        0      0 0.0.0.0:1935            0.0.0.0:*               LISTEN      26583/./OvenMediaEn
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      26583/./OvenMediaEn
```
